### PR TITLE
[App Service] `az webapp config access-restriction remove`: Fix the broken caused by AttributeError

### LINKED ISSUE #18947: WebApp:az webapp config access-restriction remove broke since 2.26.0
## Describe the bug

**Command Name**
`az webapp config access-restriction remove`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/access_restrictions.py", line 120, in remove_webapp_access_restriction
AttributeError: 'NoneType' object has no attribute 'lower'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp config access-restriction remove --resource-group {ResourceGroupName} --name {WebAppName} --action Allow --scm-site True --subnet {SubnetResourceId}`

## Expected Behavior
Successful removal of an access-restriction rule.

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.26.1

Extensions:
azure-devops 0.18.0

```
## Additional Context
I just tested this. This was working in 2.25.0 and before. With 2.26.0+ it doesn't work anymore.

### PR DESCRIPTION
**Pull request by madsd**
**Description**
Fix #18947 issue
Adding test to repro and verify fix

**Testing Guide**
Add IP address rules with service endpoint rules and remove service endpoint rule
az webapp config access-restriction add --ip-address
az webapp config access-restriction add --subnet
az webapp config access-restriction add --ip-address

az webapp config access-restriction remove --subnet

**History Notes**

[App Service] az webapp config access-restriction remove: Fix #18947 issue removing service endpoint rules

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
App Service

**Review by zhoxing-ms — APPROVED** [review]
