### ISSUE TITLE
Update from Azure 2.55.0 to 2.56.0 causes failure in python tests during build for test_extension.py and test_cloud.py

### ISSUE THREAD

**Issue by AkechiShiro** [Azure/azure-cli#28191]
### Describe the bug

The test failure are weird, because I don't think they should be happening but I'm not entirely sure why they're happening in the first place, as test were passing fully on 2.55.0 and I believe no changes happened to tests between 2.55 and 2.56, but I might be wrong.

The package is being built using Nixpkgs repo dependencies, I've checked that most dependencies are up to date in Nixpkgs repo (mostly python modules).

### Related command

No commands is related to this issue.

### Errors

```py
       last 10 log lines:
       > FAILED azure/cli/core/tests/test_cloud.py::TestCloud::test_get_known_clouds - azure.cli.core.cloud.CloudNotRegisteredException: The cloud 'AzureCloud' is...
       > FAILED azure/cli/core/tests/test_cloud.py::TestCloud::test_modify_known_cloud - azure.cli.core.cloud.CloudNotRegisteredException: The cloud 'AzureCloud' is...
       > FAILED azure/cli/core/tests/test_cloud.py::TestCloud::test_remove_known_cloud - azure.cli.core.cloud.CloudNotRegisteredException: The cloud 'AzureCloud' is...
       > FAILED azure/cli/core/tests/test_cloud.py::TestCloud::test_switch_active_cloud - azure.cli.core.cloud.CloudNotRegisteredException: The cloud 'AzureGermanClo...
       > FAILED azure/cli/core/tests/test_extension.py::TestExtensions::test_add_extension_with_preview - AttributeError: 'NoneType' object has no attribute 'startswith'
       > FAILED azure/cli/core/tests/test_extension.py::TestExtensions::test_add_extension_without_preview - AttributeError: 'NoneType' object has no attribute 'startswith'
       > FAILED azure/cli/core/tests/test_extension.py::TestExtensions::test_add_list_show_preview_extension - AttributeError: 'NoneType' object has no attribute 'startswith'
       > FAILED azure/cli/core/tests/test_extension.py::TestExtensions::test_add_preview_extension_by_defa.......                                                                  [ 41%]
azure/cli/core/tests/test_application.py .....                           [ 43%]
azure/cli/core/tests/test_cloud.py ....F...FF.FFFF                       [ 50%]
azure/cli/core/tests/test_command_recommender.py ..                      [ 50%]
azure/cli/core/tests/test_command_registration.py ..............         [ 56%]
azure/cli/core/tests/test_connection_verify.py .                         [ 56%]
azure/cli/core/tests/test_core_validators.py .                           [ 57%]
azure/cli/core/tests/test_extension.py .FFFF..........................F. [ 70%]
...........                                                              [ 75%]
azure/cli/core/tests/test_help.py ........                               [ 78%]
azure/cli/core/tests/test_keys.py ......                                 [ 80%]
azure/cli/core/tests/test_local_context.py .                             [ 81%]
azure/cli/core/tests/test_output.py ..                                   [ 81%]
azure/cli/core/tests/test_parser.py .....                                [ 83%]
azure/cli/core/tests/test_progress.py ....                               [ 85%]
azure/cli/core/tests/test_storage_validators.py .....                    [ 87%]
azure/cli/core/tests/test_style.py ......                                [ 89%]
azure/cli/core/tests/test_telemetry.py ...                               [ 91%]
azure/cli/core/tests/test_util.py ......................                 [100%]

=================================== FAILURES ===================================
______________________ TestCloud.test_cloud_is_registered ______________________

self = <azure.cli.core.tests.test_cloud.TestCloud testMethod=test_cloud_is_registered>

    def test_cloud_is_registered(self):
        cli = DummyCli()
>       self.assertTrue(cloud_is_registered(cli, AZURE_PUBLIC_CLOUD.name))
E       AssertionError: False is not true

azure/cli/core/tests/test_cloud.py:240: AssertionError
_________________ TestCloud.test_get_active_cloud_name_default _________________

self = <azure.cli.core.tests.test_cloud.TestCloud testMethod=test_get_active_cloud_name_default>

    def test_get_active_cloud_name_default(self):
        cli = DummyCli()
        expected = AZURE_PUBLIC_CLOUD.name
        actual = get_active_cloud_name(cli)
>       self.assertEqual(expected, actual)
E       AssertionError: 'AzureCloud' != 'TestCloud'
E       - AzureCloud
E       + TestCloud

azure/cli/core/tests/test_cloud.py:188: AssertionError
_____________________ TestCloud.test_get_clouds_concurrent _____________________

self = <azure.cli.core.tests.test_cloud.TestCloud testMethod=test_get_clouds_concurrent>

    def test_get_clouds_concurrent(self):
        with mock.patch('azure.cli.core.cloud.CLOUD_CONFIG_FILE', tempfile.mkstemp()[1]) as config_file:
            # Max pool_size is 61, otherwise exception will be thrown on Python 3.8 Windows:
            #     File "...Python38\lib\multiprocessing\connection.py", line 810, in _exhaustive_wait
            #       res = _winapi.WaitForMultipleObjects(L, False, timeout)
            #   ValueError: need at most 63 handles, got a sequence of length 102
            pool_size = 20
            p = multiprocessing.Pool(pool_size)
            p.map(_helper_get_clouds, range(pool_size))
            p.close()
            p.join()
            # Check we can read the file with no exceptions
            cli = DummyCli()
            configparser.ConfigParser().read(config_file)
            for kc in KNOWN_CLOUDS:
>               get_cloud(cli, kc.name)

azure/cli/core/tests/test_cloud.py:236: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

cli_ctx = <azure.cli.core.mock.DummyCli object at 0x7ffff4903f50>
cloud_name = 'AzureCloud'

    def get_cloud(cli_ctx, cloud_name):
        cloud = _get_cloud(cli_ctx, cloud_name)
        if not cloud:
>           raise CloudNotRegisteredException(cloud_name)
E           azure.cli.core.cloud.CloudNotRegisteredException: The cloud 'AzureCloud' is not registered.

azure/cli/core/cloud.py:616: CloudNotRegisteredException
_______________________ TestCloud.test_get_known_clouds ________________________

self = <azure.cli.core.tests.test_cloud.TestCloud testMethod=test_get_known_clouds>

    def test_get_known_clouds(self):
        cli = DummyCli()
        with mock.patch('azure.cli.core.cloud.CLOUD_CONFIG_FILE', tempfile.mkstemp()[1]):
            # Check that we can get all the known clouds without any exceptions
            for kc in KNOWN_CLOUDS:
>               get_cloud(cli, kc.name)

azure/cli/core/tests/test_cloud.py:195: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

cli_ctx = <azure.cli.core.mock.DummyCli object at 0x7ffff45beb90>
cloud_name = 'AzureCloud'

    def get_cloud(cli_ctx, cloud_name):
        cloud = _get_cloud(cli_ctx, cloud_name)
        if not cloud:
>           raise CloudNotRegisteredException(cloud_name)
E           azure.cli.core.cloud.CloudNotRegisteredException: The cloud 'AzureCloud' is not registered.

azure/cli/core/cloud.py:616: CloudNotRegisteredException
______________________ TestCloud.test_modify_known_cloud _______________________

self = <azure.cli.core.tests.test_cloud.TestCloud testMethod=test_modify_known_cloud>

    def test_modify_known_cloud(self):
        with mock.patch('azure.cli.core.cloud.CLOUD_CONFIG_FILE', tempfile.mkstemp()[1]) as config_file:
            cli = DummyCli()
            config = configparser.ConfigParser()
            cloud_name = AZURE_PUBLIC_CLOUD.name
>           cloud = get_cloud(cli, cloud_name)

azure/cli/core/tests/test_cloud.py:202: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

cli_ctx = <azure.cli.core.mock.DummyCli object at 0x7ffff45fdf10>
cloud_name = 'AzureCloud'

    def get_cloud(cli_ctx, cloud_name):
        cloud = _get_cloud(cli_ctx, cloud_name)
        if not cloud:
>           raise CloudNotRegisteredException(cloud_name)
E           azure.cli.core.cloud.CloudNotRegisteredException: The cloud 'AzureCloud' is not registered.

azure/cli/core/cloud.py:616: CloudNotRegisteredException
______________________ TestCloud.test_remove_known_cloud _______________________

self = <azure.cli.core.tests.test_cloud.TestCloud testMethod=test_remove_known_cloud>

    def test_remove_known_cloud(self):
        cli = DummyCli()
        with mock.patch('azure.cli.core.cloud.CLOUD_CONFIG_FILE', tempfile.mkstemp()[1]):
            with self.assertRaises(CannotUnregisterCloudException):
>               remove_cloud(cli, AZURE_PUBLIC_CLOUD.name)

azure/cli/core/tests/test_cloud.py:219: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    def remove_cloud(cli_ctx, cloud_name):
        if not _get_cloud(cli_ctx, cloud_name):
>           raise CloudNotRegisteredException(cloud_name)
E           azure.cli.core.cloud.CloudNotRegisteredException: The cloud 'AzureCloud' is not registered.

azure/cli/core/cloud.py:739: CloudNotRegisteredException
______________________ TestCloud.test_switch_active_cloud ______________________

self = <azure.cli.core.tests.test_cloud.TestCloud testMethod=test_switch_active_cloud>
subscription_setter = <function _set_active_subscription at 0x7ffff445aac0>

    @mock.patch('azure.cli.core.cloud._set_active_subscription', autospec=True)
    def test_switch_active_cloud(self, subscription_setter):
        cli = mock.MagicMock()
>       switch_active_cloud(cli, 'AzureGermanCloud')

azure/cli/core/tests/test_cloud.py:246: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

cli_ctx = <MagicMock id='140737306229648'>, cloud_name = 'AzureGermanCloud'

    def switch_active_cloud(cli_ctx, cloud_name):
        if cli_ctx.cloud.name == cloud_name:
            return
        if not _get_cloud(cli_ctx, cloud_name):
>           raise CloudNotRegisteredException(cloud_name)
E           azure.cli.core.cloud.CloudNotRegisteredException: The cloud 'AzureGermanCloud' is not registered.

azure/cli/core/cloud.py:692: CloudNotRegisteredException
________________ TestExtensions.test_add_extension_with_preview ________________

self = <azure.cli.core.tests.test_extension.TestExtensions testMethod=test_add_extension_with_preview>

    def test_add_extension_with_preview(self):
        extension_name = "extension-test-pkg"
        extension1 = 'extension_test_pkg-1.0.0b1-py3-none-any.whl'
        extension2 = 'extension_test_pkg-1.2.3-py3-none-any.whl'
        extension3 = 'extension_test_pkg-1.4.1a1-py3-none-any.whl'
    
        mocked_index_data = {
            extension_name: [
                mock_ext(extension1, version='1.0.0b1', download_url=_get_test_data_file(extension1)),
                mock_ext(extension2, version='1.2.3', download_url=_get_test_data_file(extension2)),
                mock_ext(extension3, version='1.4.1a1', download_url=_get_test_data_file(extension3))
            ]
        }
    
        with mock.patch('azure.cli.core.extension._resolve.get_index_extensions',
                        return_value=mocked_index_data):
>           add_extension(self.cmd, extension_name=extension_name, allow_preview=True)

azure/cli/core/tests/test_extension.py:377: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
azure/cli/core/extension/operations.py:349: in add_extension
    extension_name = _add_whl_ext(cli_ctx=cmd_cli_ctx, source=source, ext_sha256=ext_sha256,
azure/cli/core/extension/operations.py:167: in _add_whl_ext
    with HomebrewPipPatch():
azure/cli/core/extension/_homebrew_patch.py:29: in __enter__
    if not is_homebrew():
azure/cli/core/extension/_homebrew_patch.py:17: in is_homebrew
    return any((p.startswith(HOMEBREW_CELLAR_PATH) for p in sys.path))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

.0 = <list_iterator object at 0x7ffff4484670>

>   return any((p.startswith(HOMEBREW_CELLAR_PATH) for p in sys.path))
E   AttributeError: 'NoneType' object has no attribute 'startswith'

azure/cli/core/extension/_homebrew_patch.py:17: AttributeError
______________ TestExtensions.test_add_extension_without_preview _______________

self = <azure.cli.core.tests.test_extension.TestExtensions testMethod=test_add_extension_without_preview>

    def test_add_extension_without_preview(self):
        extension_name = "extension-test-pkg"
        extension1 = 'extension_test_pkg-1.0.0b1-py3-none-any.whl'
        extension2 = 'extension_test_pkg-1.2.3-py3-none-any.whl'
        extension3 = 'extension_test_pkg-1.4.1a1-py3-none-any.whl'
    
        mocked_index_data = {
            extension_name: [
                mock_ext(extension1, version='1.0.0b1', download_url=_get_test_data_file(extension1)),
                mock_ext(extension2, version='1.2.3', download_url=_get_test_data_file(extension2)),
                mock_ext(extension3, version='1.4.1a1', download_url=_get_test_data_file(extension3))
            ]
        }
        with mock.patch('azure.cli.core.extension._resolve.get_index_extensions',
                        return_value=mocked_index_data):
>           add_extension(self.cmd, extension_name=extension_name, allow_preview=False)

azure/cli/core/tests/test_extension.py:355: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
azure/cli/core/extension/operations.py:349: in add_extension
    extension_name = _add_whl_ext(cli_ctx=cmd_cli_ctx, source=source, ext_sha256=ext_sha256,
azure/cli/core/extension/operations.py:167: in _add_whl_ext
    with HomebrewPipPatch():
azure/cli/core/extension/_homebrew_patch.py:29: in __enter__
    if not is_homebrew():
azure/cli/core/extension/_homebrew_patch.py:17: in is_homebrew
    return any((p.startswith(HOMEBREW_CELLAR_PATH) for p in sys.path))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

.0 = <list_iterator object at 0x7ffff44a13f0>

>   return any((p.startswith(HOMEBREW_CELLAR_PATH) for p in sys.path))
E   AttributeError: 'NoneType' object has no attribute 'startswith'

azure/cli/core/extension/_homebrew_patch.py:17: AttributeError
_____________ TestExtensions.test_add_list_show_preview_extension ______________

self = <azure.cli.core.tests.test_extension.TestExtensions testMethod=test_add_list_show_preview_extension>

    def test_add_list_show_preview_extension(self):
        test_ext_source = _get_test_data_file('ml-2.0.0a1-py3-none-any.whl')
        with mock.patch('azure.cli.core.extension.operations.logger') as mock_logger:
>           add_extension(cmd=self.cmd, source=test_ext_source, allow_preview=True)

azure/cli/core/tests/test_extension.py:316: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
azure/cli/core/extension/operations.py:349: in add_extension
    extension_name = _add_whl_ext(cli_ctx=cmd_cli_ctx, source=source, ext_sha256=ext_sha256,
azure/cli/core/extension/operations.py:167: in _add_whl_ext
    with HomebrewPipPatch():
azure/cli/core/extension/_homebrew_patch.py:29: in __enter__
    if not is_homebrew():
azure/cli/core/extension/_homebrew_patch.py:17: in is_homebrew
    return any((p.startswith(HOMEBREW_CELLAR_PATH) for p in sys.path))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

.0 = <list_iterator object at 0x7ffff4487850>

>   return any((p.startswith(HOMEBREW_CELLAR_PATH) for p in sys.path))
E   AttributeError: 'NoneType' object has no attribute 'startswith'

azure/cli/core/extension/_homebrew_patch.py:17: AttributeError
_____________ TestExtensions.test_add_preview_extension_by_default _____________

self = <azure.cli.core.tests.test_extension.TestExtensions testMethod=test_add_preview_extension_by_default>

    def test_add_preview_extension_by_default(self):
        test_ext_source = _get_test_data_file('extension_test_pkg-1.2.3-py3-none-any.whl')
        with mock.patch('azure.cli.core.extension.operations.logger') as mock_logger:
>           add_extension(cmd=self.cmd, source=test_ext_source)

azure/cli/core/tests/test_extension.py:329: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
azure/cli/core/extension/operations.py:349: in add_extension
    extension_name = _add_whl_ext(cli_ctx=cmd_cli_ctx, source=source, ext_sha256=ext_sha256,
azure/cli/core/extension/operations.py:167: in _add_whl_ext
    with HomebrewPipPatch():
azure/cli/core/extension/_homebrew_patch.py:29: in __enter__
    if not is_homebrew():
azure/cli/core/extension/_homebrew_patch.py:17: in is_homebrew
    return any((p.startswith(HOMEBREW_CELLAR_PATH) for p in sys.path))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

.0 = <list_iterator object at 0x7ffff4589600>

>   return any((p.startswith(HOMEBREW_CELLAR_PATH) for p in sys.path))
E   AttributeError: 'NoneType' object has no attribute 'startswith'

azure/cli/core/extension/_homebrew_patch.py:17: AttributeError
______________ TestExtensions.test_update_extension_with_preview _______________

self = <azure.cli.core.tests.test_extension.TestExtensions testMethod=test_update_extension_with_preview>

    def test_update_extension_with_preview(self):
        extension_name = "extension-test-pkg"
        extension1 = 'extension_test_pkg-1.0.0b1-py3-none-any.whl'
        extension2 = 'extension_test_pkg-1.2.3-py3-none-any.whl'
        extension3 = 'extension_test_pkg-1.4.1a1-py3-none-any.whl'
    
        mocked_index_data = {
            extension_name: [
                mock_ext(extension1, version='1.0.0b1', download_url=_get_test_data_file(extension1)),
                mock_ext(extension2, version='1.2.3', download_url=_get_test_data_file(extension2)),
                mock_ext(extension3, version='1.4.1a1', download_url=_get_test_data_file(extension3))
            ]
        }
        with mock.patch('azure.cli.core.extension._resolve.get_index_extensions',
                        return_value=mocked_index_data):
>           add_extension(self.cmd, extension_name=extension_name, allow_preview=False)

azure/cli/core/tests/test_extension.py:416: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
azure/cli/core/extension/operations.py:349: in add_extension
    extension_name = _add_whl_ext(cli_ctx=cmd_cli_ctx, source=source, ext_sha256=ext_sha256,
azure/cli/core/extension/operations.py:167: in _add_whl_ext
    with HomebrewPipPatch():
azure/cli/core/extension/_homebrew_patch.py:29: in __enter__
    if not is_homebrew():
azure/cli/core/extension/_homebrew_patch.py:17: in is_homebrew
    return any((p.startswith(HOMEBREW_CELLAR_PATH) for p in sys.path))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

.0 = <list_iterator object at 0x7ffff458a770>

>   return any((p.startswith(HOMEBREW_CELLAR_PATH) for p in sys.path))
E   AttributeError: 'NoneType' object has no attribute 'startswith'

azure/cli/core/extension/_homebrew_patch.py:17: AttributeError
=============================== warnings summary ===============================
azure/cli/core/tests/test_aaz_operation.py:382
  /build/azure-cli-2.56.0-src/src/azure-cli-core/azure/cli/core/tests/test_aaz_operation.py:382: DeprecationWarning: invalid escape sequence '\['
    with self.assertRaisesRegex(InvalidArgumentValueError, "Couldn't find '\[1\]' in ''. Available options: \['d', 'd2', 'i', 'l', 'l2', 's'\]"):

azure/cli/core/tests/test_aaz_operation.py:392
  /build/azure-cli-2.56.0-src/src/azure-cli-core/azure/cli/core/tests/test_aaz_operation.py:392: DeprecationWarning: invalid escape sequence '\['
    with self.assertRaisesRegex(InvalidArgumentValueError, "Couldn't find 'props' in ''. Available options: \['d', 'd2', 'i', 'l', 'l2', 's'\]"):

azure/cli/core/tests/test_aaz_operation.py:402
  /build/azure-cli-2.56.0-src/src/azure-cli-core/azure/cli/core/tests/test_aaz_operation.py:402: DeprecationWarning: invalid escape sequence '\['
    with self.assertRaisesRegex(InvalidArgumentValueError, "Couldn't find 'o' in 'l\[0\]'. Available options: \['p', 's'\]"):

azure/cli/core/tests/test_aaz_operation.py:444
  /build/azure-cli-2.56.0-src/src/azure-cli-core/azure/cli/core/tests/test_aaz_operation.py:444: DeprecationWarning: invalid escape sequence '\['
    with self.assertRaisesRegex(InvalidArgumentValueError, "Couldn't find 't' in 'l\[1\]'. Available options: \['p', 's'\]"):

azure/cli/core/tests/test_aaz_operation.py:464
  /build/azure-cli-2.56.0-src/src/azure-cli-core/azure/cli/core/tests/test_aaz_operation.py:464: DeprecationWarning: invalid escape sequence '\('
    with self.assertRaisesRegex(InvalidArgumentValueError, "Expect <class 'str'>, got 3 \(<class 'int'>\)"):

azure/cli/core/tests/test_aaz_operation.py:484
  /build/azure-cli-2.56.0-src/src/azure-cli-core/azure/cli/core/tests/test_aaz_operation.py:484: DeprecationWarning: invalid escape sequence '\['
    with self.assertRaisesRegex(InvalidArgumentValueError, "Couldn't find '\[10\]' in 'd'. Available options: \['a', 'b', 'c'\]"):

azure/cli/core/tests/test_aaz_operation.py:495
  /build/azure-cli-2.56.0-src/src/azure-cli-core/azure/cli/core/tests/test_aaz_operation.py:495: DeprecationWarning: invalid escape sequence '\('
    with self.assertRaisesRegex(InvalidArgumentValueError, "Expect <class 'int'>, got a \(<class 'str'>\)"):

azure/cli/core/extension/__init__.py:11
  /build/azure-cli-2.56.0-src/src/azure-cli-core/azure/cli/core/extension/__init__.py:11: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
    from distutils.sysconfig import get_python_lib  # pylint: disable=deprecated-module

azure/cli/core/extension/__init__.py:11
  /build/azure-cli-2.56.0-src/src/azure-cli-core/azure/cli/core/extension/__init__.py:11: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
    from distutils.sysconfig import get_python_lib  # pylint: disable=deprecated-module

azure/cli/core/tests/test_help_loaders.py:13
  /build/azure-cli-2.56.0-src/src/azure-cli-core/azure/cli/core/tests/test_help_loaders.py:13: PytestCollectionWarning: cannot collect test class 'TestCommandLoader' because it has a __init__ constructor (from: azure/cli/core/tests/test_help_loaders.py)
    class TestCommandLoader(AzCommandsLoader):

azure/cli/core/tests/test_application.py::TestApplication::test_client_request_id_is_refreshed_after_execution
  /build/azure-cli-2.56.0-src/src/azure-cli-core/azure/cli/core/tests/test_application.py:56: DeprecationWarning: Please use assertNotEqual instead.
    self.assertNotEquals(old_id, cli.data['headers']['x-ms-client-request-id'])

azure/cli/core/tests/test_application.py::TestApplication::test_client_request_id_is_refreshed_correctly
  /build/azure-cli-2.56.0-src/src/azure-cli-core/azure/cli/core/tests/test_application.py:35: DeprecationWarning: Please use assertNotEqual instead.
    self.assertNotEquals(old_id, cli.data['headers']['x-ms-client-request-id'])

azure/cli/core/tests/test_command_registration.py: 10 warnings
  /nix/store/asiphbpiy2gmidfm3xbwcikayhs66289-python3-3.11.7/lib/python3.11/unittest/case.py:1176: DeprecationWarning: assertDictContainsSubset is deprecated
    warnings.warn('assertDictContainsSubset is deprecated',

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED azure/cli/core/tests/test_cloud.py::TestCloud::test_cloud_is_registered - AssertionError: False is not true
FAILED azure/cli/core/tests/test_cloud.py::TestCloud::test_get_active_cloud_name_default - AssertionError: 'AzureCloud' != 'TestCloud'
FAILED azure/cli/core/tests/test_cloud.py::TestCloud::test_get_clouds_concurrent - azure.cli.core.cloud.CloudNotRegisteredException: The cloud 'AzureCloud' is...
FAILED azure/cli/core/tests/test_cloud.py::TestCloud::test_get_known_clouds - azure.cli.core.cloud.CloudNotRegisteredException: The cloud 'AzureCloud' is...
FAILED azure/cli/core/tests/test_cloud.py::TestCloud::test_modify_known_cloud - azure.cli.core.cloud.CloudNotRegisteredException: The cloud 'AzureCloud' is...
FAILED azure/cli/core/tests/test_cloud.py::TestCloud::test_remove_known_cloud - azure.cli.core.cloud.CloudNotRegisteredException: The cloud 'AzureCloud' is...
FAILED azure/cli/core/tests/test_cloud.py::TestCloud::test_switch_active_cloud - azure.cli.core.cloud.CloudNotRegisteredException: The cloud 'AzureGermanClo...
FAILED azure/cli/core/tests/test_extension.py::TestExtensions::test_add_extension_with_preview - AttributeError: 'NoneType' object has no attribute 'startswith'
FAILED azure/cli/core/tests/test_extension.py::TestExtensions::test_add_extension_without_preview - AttributeError: 'NoneType' object has no attribute 'startswith'
FAILED azure/cli/core/tests/test_extension.py::TestExtensions::test_add_list_show_preview_extension - AttributeError: 'NoneType' object has no attribute 'startswith'
FAILED azure/cli/core/tests/test_extension.py::TestExtensions::test_add_preview_extension_by_default - AttributeError: 'NoneType' object has no attribute 'startswith'
FAILED azure/cli/core/tests/test_extension.py::TestExtensions::test_update_extension_with_preview - AttributeError: 'NoneType' object has no attribute 'startswith'
========== 12 failed, 236 passed, 3 deselected, 22 warnings in 2.07s ===========
error: builder for '/nix/store/ay9pghkpxw6q4s531azp6z67pqjwqn13-python3.11-azure-cli-core-2.56.0.drv' failed with exit code 1;
       last 10 log lines:
       > FAILED azure/cli/core/tests/test_cloud.py::TestCloud::test_get_known_clouds - azure.cli.core.cloud.CloudNotRegisteredException: The cloud 'AzureCloud' is...
       > FAILED azure/cli/core/tests/test_cloud.py::TestCloud::test_modify_known_cloud - azure.cli.core.cloud.CloudNotRegisteredException: The cloud 'AzureCloud' is...
       > FAILED azure/cli/core/tests/test_cloud.py::TestCloud::test_remove_known_cloud - azure.cli.core.cloud.CloudNotRegisteredException: The cloud 'AzureCloud' is...
       > FAILED azure/cli/core/tests/test_cloud.py::TestCloud::test_switch_active_cloud - azure.cli.core.cloud.CloudNotRegisteredException: The cloud 'AzureGermanClo...
       > FAILED azure/cli/core/tests/test_extension.py::TestExtensions::test_add_extension_with_preview - AttributeError: 'NoneType' object has no attribute 'startswith'
       > FAILED azure/cli/core/tests/test_extension.py::TestExtensions::test_add_extension_without_preview - AttributeError: 'NoneType' object has no attribute 'startswith'
       > FAILED azure/cli/core/tests/test_extension.py::TestExtensions::test_add_list_show_preview_extension - AttributeError: 'NoneType' object has no attribute 'startswith'
       > FAILED azure/cli/core/tests/test_extension.py::TestExtensions::test_add_preview_extension_by_defa-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED azure/cli/core/tests/test_cloud.py::TestCloud::test_cloud_is_registered - AssertionError: False is not true
FAILED azure/cli/core/tests/test_cloud.py::TestCloud::test_get_active_cloud_name_default - AssertionError: 'AzureCloud' != 'TestCloud'
FAILED azure/cli/core/tests/test_cloud.py::TestCloud::test_get_clouds_concurrent - azure.cli.core.cloud.CloudNotRegisteredException: The cloud 'AzureCloud' is...
FAILED azure/cli/core/tests/test_cloud.py::TestCloud::test_get_known_clouds - azure.cli.core.cloud.CloudNotRegisteredException: The cloud 'AzureCloud' is...
FAILED azure/cli/core/tests/test_cloud.py::TestCloud::test_modify_known_cloud - azure.cli.core.cloud.CloudNotRegisteredException: The cloud 'AzureCloud' is...
FAILED azure/cli/core/tests/test_cloud.py::TestCloud::test_remove_known_cloud - azure.cli.core.cloud.CloudNotRegisteredException: The cloud 'AzureCloud' is...
FAILED azure/cli/core/tests/test_cloud.py::TestCloud::test_switch_active_cloud - azure.cli.core.cloud.CloudNotRegisteredException: The cloud 'AzureGermanClo...
FAILED azure/cli/core/tests/test_extension.py::TestExtensions::test_add_extension_with_preview - AttributeError: 'NoneType' object has no attribute 'startswith'
FAILED azure/cli/core/tests/test_extension.py::TestExtensions::test_add_extension_without_preview - AttributeError: 'NoneType' object has no attribute 'startswith'
FAILED azure/cli/core/tests/test_extension.py::TestExtensions::test_add_list_show_preview_extension - AttributeError: 'NoneType' object has no attribute 'startswith'
FAILED azure/cli/core/tests/test_extension.py::TestExtensions::test_add_preview_extension_by_default - AttributeError: 'NoneType' object has no attribute 'startswith'
FAILED azure/cli/core/tests/test_extension.py::TestExtensions::test_update_extension_with_preview - AttributeError: 'NoneType' object has no attribute 'startswith'
========== 12 failed, 236 passed, 3 deselected, 22 warnings in 2.07s ===========
```

### Issue script & Debug output

Here is the previous derivation that works on 2.55.0 : https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/admin/azure-cli/default.nix
Along with the pinned python modules packages : https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/admin/azure-cli/python-packages.nix

The new one just updates the version to 2.56.0, I have updated the pinned dependencies that changed by diffing requirements.txt that was tagged for azure-cli 2.55.0 and azure-cli 2.56.0 release tag. It still did not help solve the issue.

### Expected behavior

Tests should be passing.

### Environment Summary

Not relevant

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by AkechiShiro** [comment]
Hi @Bebound, we believe it's due to a regression from the last release, @yonzhan I believe this is a bug.

The self-test of the `azure-cli` does pass if we disable all `pytests` tests when building the latest release.

**Comment by bebound** [comment]
I don't know how you build the test env, this does not happen in our pipeline.
The error message is strange, so I guess something is wrong from the nixpkg side:
```
>   return any((p.startswith(HOMEBREW_CELLAR_PATH) for p in sys.path))
E   AttributeError: 'NoneType' object has no attribute 'startswith'
```
Why `None` is in `sys.path`?

**Comment by AkechiShiro** [comment]
Thanks @bebound, we'll investigate further on our side then.

**Comment by AkechiShiro** [comment]
Closing this issue, as I need to do a more thorough investigation on my side.
