### ISSUE TITLE
Unable to create a deployment slot in Azure function in CLI 2.23.0 

### ISSUE THREAD

**Issue by vivek-bsn** [Azure/azure-cli#18080]
**Describe the bug**
The following command should create a deployment slot on the function app -

`az functionapp deployment slot create --name vb-func-test-1 --resource-group vb-func-apps --slot staging --configuration-source vb-func-test-1 `

Reference: https://docs.microsoft.com/en-us/cli/azure/functionapp/deployment/slot?view=azure-cli-latest#az_functionapp_deployment_slot_create

But when we execute this command in Azure Cloud Shell, we are getting following error - 
**The command failed with an unexpected error. Here is the traceback:
Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError:'str' object has no attribute 'get'**

**To Reproduce**
Go to Cloud Shell in Azure portal and execute the command to create a deployment slot in function app - 
az functionapp deployment slot create --name
                                      --resource-group
                                      --slot
                                      [--configuration-source]
                                      [--subscription]

**Expected behavior**
The command should execute successfully and create a deployment slot for the function app.

**Environment summary**
![image](https://user-images.githubusercontent.com/79462763/118172233-23dfd680-b3fa-11eb-959c-5b5a055f7948.png)

**Comment by yonzhan** [comment]
route to service team

**Comment by eversleep** [comment]
We have the same issue, command that worked with both 2.19.1 and 2.22.1 stopped working when updating the cli to 2.23.0.
After the update we get the same message as the author both in devops and locally.

**Comment by cannehag** [comment]
I have the exact same problem both locally and in DevOps.

This is really urgent because we can't deploy our services to our production environment because of this. And from what I can tell there is no way around it either since it's not possible to specify what version of the cli to use.

**Comment by vivekbsn-msft** [comment]
We were able to get around the issue by downgrading Azure CLI to 2.22.0 using a YAML script. This worked out for us -

```
steps:

# Updating the python version available on the linux agent

- task: UsePythonVersion@0

inputs:

versionSpec: '3.x'

architecture: 'x64'

# Updating pip to latest which is required by the Azure DevOps extension

- script: python -m pip install --upgrade pip

displayName: 'Upgrade pip'

**# Installing Azure CLI - 2.22.0**

**- script: pip install azure-cli==2.22.0**

displayName: 'upgrade azure cli'

- script: az --version

displayName: 'Show Azure CLI version'

- task: AzureCLI@1

displayName: 'Azure CLI '

inputs:

azureSubscription: 'test_sub_id (e91xxxxx-xxxx-43ff-xxxx-xxxxx66b25)'

scriptLocation: inlineScript

inlineScript: 'az functionapp deployment slot create --name vb-func-test-1 --resource-group vb-func-apps --slot staging --configuration-source vb-func-test-1'
```

Reference - https://docs.microsoft.com/en-us/azure/devops/cli/azure-devops-cli-in-yaml?view=azure-devops#for-windows-azure-pipelines-steps-winyml

**Comment by CReich02** [comment]
This is the same bug that I reported in https://github.com/Azure/azure-cli/issues/18072 . It looks like there are various other issues with version 2.23.0 that have a very similar stack trace in the error message.

Thanks for the workaround, this seems to work for now.

**Comment by cannehag** [comment]
Could we please get some priority on this @yonzhan ?

**Comment by yonzhan** [comment]
functionapp service team should look into this issue

**Comment by vivekbsn-msft** [comment]
@cannehag Hopefully all these issues are expected to get fixed in this release - https://github.com/Azure/azure-cli/milestone/105
If it is critical, you can give this workaround a shot - https://github.com/Azure/azure-cli/issues/18080#issuecomment-841320335

> Could we please get some priority on this @yonzhan ?

**Comment by cannehag** [comment]
@vivekbsn-msft So, you are saying that you drop a new release that breaks things, and then tell people to wait for another release which is 79% __NOT__ completed? Isn't a bugfix release even considered here ?

**Comment by vivekbsn-msft** [comment]
@cannehag All these breaking changes are expected to get fixed in that release. I understand your concern, unfortunately the team I work for is also affected by this issue and we got the guidance to downgrade the cli version intermittently. 

> @vivekbsn-msft So, you are saying that you drop a new release that breaks things, and then tell people to wait for another release which is 79% **NOT** completed? Isn't a bugfix release even considered here ?

**Comment by cannehag** [comment]
@vivekbsn-msft I really find it hard to understand that such a breaking change can be released if other teams inside Microsoft also are affected by it.
Not saying this is your fault. Just saying it's really annoying and frustrating when things break like this.

**Comment by sharebear** [comment]
The above workaround doesn't work for me as I'm using GitHub Actions with a self-hosted runner and installing the cli using the ubuntu package with unattended upgrades enabled for security reasons. This was my workaround that appears to be working so far;

```
sudo apt-get install azure-cli=2.22.1-1~bionic
sudo apt-mark hold azure-cli
```

I've also used the watch feature of GitHub to subscribe to release notifications so that I know when I can release the hold. Although I do share the surprise that such a severe breakage doesn't warrant a bugfix release.

**Comment by gzuber** [comment]
Thanks for reporting this -- I'm tracking this across several github issues and am looking into getting a fix out ASAP. Sorry for the inconvenience.

**Comment by cannehag** [comment]
@gzuber 2.23.0 was the version where the problems started. 2.24.0 is the solution

**Comment by MichaelDenwood** [comment]
It appears in 2.27.1 when running against Azure DevOps self hosted agent.  My command is slightly different:

`az functionapp deployment slot auto-swap --slot staging -g 'resourcegroup'  -n 'appname'`

This command (-g and -n changed for privacy) works fine from my local computer.  Running cli version 2.19.1  However, when running the latest version in the agent (2.27.1) it produces the dreaded error:

`2021-08-12T18:31:20.1652453Z ERROR: Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
`

Changing the version of the API isn't an option as this latest version corrects another issue we have in this same script. 

I wanted to let you know that It's Back!

**Comment by panchagnula** [comment]
this is fixed - please re-open if this still repros with the latest cli-version
