### ISSUE TITLE
Exception when running az network vnet list 

### ISSUE THREAD

**Issue by Kamran-Bilgrami** [Azure/azure-cli#16482]
## Describe the bug

**Command Name**
`az network vnet list`

**Errors:**
```
cannot import name 'BatchManagementClient' from 'azure.mgmt.batch' (/usr/lib/python3/dist-packages/azure/mgmt/batch/__init__.py)
Traceback (most recent call last):
python3/dist-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 558, in execute
    self.commands_loader.load_arguments(command)
...
network/private_link_resource_and_endpoint_connections/resource_providers/batch_provider.py, ln 6, in <module>
    from azure.mgmt.batch import BatchManagementClient
ImportError: cannot import name 'BatchManagementClient' from 'azure.mgmt.batch' (/usr/lib/python3/dist-packages/azure/mgmt/batch/__init__.py)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network vnet list`

## Environment Summary
```
Linux-5.9.0-kali1-amd64-x86_64-with-glibc2.31
Python 3.9.1
Installer: PIP

azure-cli 2.17.1

Extensions:
interactive 0.4.4
azure-devops 0.19.0

```

**Comment by yonzhan** [comment]
network

**Comment by Kamran-Bilgrami** [comment]
Today I got a newer version of az cli

```
kali@kali:~$ az --version
azure-cli                         2.18.0

core                              2.18.0
telemetry                          1.0.6

Extensions:
interactive                        0.4.4
azure-devops                      0.19.0

Python location '/usr/bin/python3'
Extensions directory '/home/kali/.azure/cliextensions'
Extensions system directory '/usr/lib/python3/dist-packages/azure-cli-extensions'

Python (Linux) 3.9.1+ (default, Jan 20 2021, 14:49:22) 
[GCC 10.2.1 20210110]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
```
But still get exception as shown below
```
kali@kali:~$ az network vnet list
CLIInternalError: The command failed with an unexpected error. Here is the traceback:
cannot import name 'BatchManagementClient' from 'azure.mgmt.batch' (/usr/lib/python3/dist-packages/azure/mgmt/batch/__init__.py)
Traceback (most recent call last):                                                                                                                                                                                                         
  File "/home/kali/.local/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke                                                                                                                                                   
    cmd_result = self.invocation.execute(args)                                                                                                                                                                                             
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 558, in execute                                                                                                                                          
    self.commands_loader.load_arguments(command)                                                                                                                                                                                           
  File "/usr/lib/python3/dist-packages/azure/cli/core/__init__.py", line 481, in load_arguments                                                                                                                                            
    loader.load_arguments(command)  # this adds entries to the argument registries                                                                                                                                                         
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/network/__init__.py", line 39, in load_arguments                                                                                                                          
    load_arguments(self, command)                                                                                                                                                                                                          
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/network/_params.py", line 2000, in load_arguments                                                                                                                         
    from azure.cli.command_modules.network.private_link_resource_and_endpoint_connections.custom import TYPE_CLIENT_MAPPING, register_providers                                                                                            
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/network/private_link_resource_and_endpoint_connections/custom.py", line 9, in <module>                                                                                    
    from .resource_providers.batch_provider import BatchPrivateEndpointClient                                                                                                                                                              
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/network/private_link_resource_and_endpoint_connections/resource_providers/batch_provider.py", line 6, in <module>                                                         
    from azure.mgmt.batch import BatchManagementClient                                                                                                                                                                                     
ImportError: cannot import name 'BatchManagementClient' from 'azure.mgmt.batch' (/usr/lib/python3/dist-packages/azure/mgmt/batch/__init__.py)                                                                                              
To open an issue, please run: 'az feedback'
```
The issue was reported against az version  2.16.0 and 2.17.0 whereas now I have 2.18.0 running. What version of cli this issue is planned to be addressed? 

Thanks

**Comment by msyyc** [comment]
I could not reproduce it. my python version is '3.6.9'. Could you have a try to downgrade python?

**Comment by Kamran-Bilgrami** [comment]
@msyyc 
> I could not reproduce it. my python version is '3.6.9'. Could you have a try to downgrade python?

The original issue was reported with Python 3.9.1 BTW. I can give downgrading a try but 
1) Can you confirm if the issue reported got addressed in az cli version 2.18.0? 
2) Let's say it works with python 3.6.9. Will you require anyone encountering the issue (while using python 3.9.1) to downgrade python?

**Comment by msyyc** [comment]
I upgrade the python version to '3.9.1', but I could not reproduce it, either.

env info
==
System : Ubuntu 18.04
Python : 3.9.1
azure-cli                         2.18.0
core                              2.18.0

please use 'pip list' to check version of 'azure-mgmt-batch'. It should be '9.0.0'

**Comment by jsntcy** [comment]
BTW, we'll have 7 days Chinese New Year holiday from tomorrow, please expect delay response.

**Comment by Kamran-Bilgrami** [comment]
> please use 'pip list' to check version of 'azure-mgmt-batch'. It should be '9.0.0'

```
kali@kali:~$ pip list | grep azure-mgmt-batch
azure-mgmt-batch                                 9.0.0
azure-mgmt-batchai                               2.0.0
```

**Comment by jsntcy** [comment]
@msyyc, any update on this issue?

**Comment by Kamran-Bilgrami** [comment]
I upgraded my azure CLI to version 2.19.0. I am not able to reproduce the issue anymore. Thanks for all your help.
