### ISSUE TITLE
Error when running az appservice ase list-addresses -n ASEName

### ISSUE THREAD

**Issue by djr29578** [Azure/azure-cli#13140]
## Describe the bug
When running this command a list of VIP addresses should be the output.  This worked on az cli verison 2.0.78 but started failing when I upgraded to 2.4

**Command Name**
`az appservice ase list-addresses`

**Errors:**
```
'AppServiceEnvironmentsOperations' object has no attribute 'list_vips'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 631, in execute
    raise ex
cli/core/commands/__init__.py, ln 695, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
azure/cli/core/__init__.py, ln 574, in default_command_handler
    return op(**command_args)
cli/command_modules/appservice/appservice_environment.py, ln 100, in list_appserviceenvironment_addresses
    return ase_client.list_vips(resource_group_name, name)
AttributeError: 'AppServiceEnvironmentsOperations' object has no attribute 'list_vips'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az appservice ase list-addresses -n {}`

## Expected Behavior
Expected outcome based on command ran in previous versions of AZ CLI (replaced IP addresses with ##):    

{
  "internalIpAddress": null,
  "outboundIpAddresses": [
    "##"
  ],
  "serviceIpAddress": "##",
  "vipMappings": [
    {
      "inUse": false,
      "internalHttpPort": 20003,
      "internalHttpsPort": 20001,
      "serviceName": null,
      "virtualIp": "##"
    },
    {
      "inUse": false,
      "internalHttpPort": 20004,
      "internalHttpsPort": 20002,
      "serviceName": null,
      "virtualIp": "##"
    }
  ]
}

## Environment Summary
```
Linux-4.4.0-18362-Microsoft-x86_64-with-debian-buster-sid
Python 3.6.5
Installer: DEB

azure-cli 2.4.0

Extensions:
application-insights 0.1.1

```

**Comment by yonzhan** [comment]
appservice

**Comment by yungezz** [comment]
bug

**Comment by djr29578** [comment]
Is there any update to the timeline on when this fix will be complete?

**Comment by panchagnula** [comment]
@madsd FYI,

**Comment by panchagnula** [comment]
closing this since the fix is merged
