### ISSUE TITLE
Error when running az network vnet create command

### ISSUE THREAD

**Issue by dylanfprice** [Azure/azure-cli#21090]
## Describe the bug

**Command Name**
`az network dns record-set cname create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'standard_medium'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 556, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/lib/python3/dist-packages/azure/cli/core/__init__.py", line 518, in load_arguments
    loader.load_arguments(command)  # this adds entries to the argument registries
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/network/__init__.py", line 39, in load_arguments
    load_arguments(self, command)
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/network/_params.py", line 135, in load_arguments
    c.argument('sku', arg_group='Gateway', help='The name of the SKU.', arg_type=get_enum_type(ApplicationGatewaySkuName), default=ApplicationGatewaySkuName.standard_medium.value)
AttributeError: 'NoneType' object has no attribute 'standard_medium'

```

## To Reproduce:

Very easy to repro for me:

- `az network dns record-set cname create --help`

## Expected Behavior

No error! For the above repro, the help info should be printed to the console.

## Environment Summary
```
Linux-5.15.0-2-amd64-x86_64-with-glibc2.33, Debian GNU/Linux bookworm/sid
Python 3.9.9
Installer: DEB

azure-cli 2.32.0

Extensions:
communication 1.1.0
azure-devops 0.22.0

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by dylanfprice** [comment]
I think this is the same as #20886 except that I am seeing it on version `2.32.0`

**Comment by yonzhan** [comment]
network

**Comment by YuanyuanNi** [comment]
Hi, 
     'az network dns record-set cname create --help' works well on 2.33.0 version, maybe you can upgrade your CLi version to the 2.33.0.
Best wishes.

**Comment by dylanfprice** [comment]
It works now! Thanks.
