### ISSUE TITLE
az aks list fails in ADO pipeline using 2.41

### ISSUE THREAD

**Issue by alan-marcinkowski** [Azure/azure-cli#24188]
## Describe the bug
Execution of AzureCLI@2 task fails.

**Command Name**
`az aks list`

**Errors:**
```
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: 'ContainerServiceClientConfiguration' object has no attribute 'api_version'
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/acs/custom.py", line 724, in aks_list
    return _remove_nulls(list(managed_clusters))
  File "/opt/az/lib/python3.10/site-packages/azure/core/paging.py", line 129, in __next__
    return next(self._page_iterator)
  File "/opt/az/lib/python3.10/site-packages/azure/core/paging.py", line 76, in __next__
    self._response = self._get_next(self.continuation_token)
  File "/opt/az/lib/python3.10/site-packages/azure/mgmt/containerservice/v2022_07_01/operations/_managed_clusters_operations.py", line 977, in get_next
    request = prepare_request(next_link)
  File "/opt/az/lib/python3.10/site-packages/azure/mgmt/containerservice/v2022_07_01/operations/_managed_clusters_operations.py", line 962, in prepare_request
    _next_request_params["api-version"] = self._config.api_version
AttributeError: 'ContainerServiceClientConfiguration' object has no attribute 'api_version'
To open an issue, please run: 'az feedback'

```

## To Reproduce:
      RESOURCE_GROUP=$(az aks list --query "[?name=='${CLUSTER_NAME}'].resourceGroup|[0]" -o tsv)

- _Put any pre-requisite steps here..._
- ``

## Expected Behavior
Should return resource group for the specified cluster

## Environment Summary
```ADO linux - custom build agent - Ubuntu/bionic (18.04)

azure-cli 2.41.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by alan-marcinkowski** [comment]
Failed equivalently on Windows as well using 2.41.0 ... but works with 2.40.0:

```
 az aks list --query "[?name=='ueclu-dgnaks001'].resourceGroup|[0]" -o tsv
The command failed with an unexpected error. Here is the traceback:
'ContainerServiceClientConfiguration' object has no attribute 'api_version'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/custom.py", line 724, in aks_list
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/paging.py", line 129, in __next__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/paging.py", line 76, in __next__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/containerservice/v2022_07_01/operations/_managed_clusters_operations.py", line 977, in get_next
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/containerservice/v2022_07_01/operations/_managed_clusters_operations.py", line 962, in prepare_request
AttributeError: 'ContainerServiceClientConfiguration' object has no attribute 'api_version'
To open an issue, please run: 'az feedback'
```

**Comment by PramodValavala-MSFT** [comment]
@alan-marcinkowski While not the same command, looks like this is the same as this issue - #24185. Investigating.

**Comment by alan-marcinkowski** [comment]
Sure does.

**Comment by itsmeabhijeet** [comment]
Same error here with AZ CLI v2.41, but works with 2.40.0. Hoping it gets fixed soon as our pipelines rely on latest version.

**Comment by alan-marcinkowski** [comment]
We have a custom agent pool so were able to forcibly replace the az version back to 2.40.0. Perhaps that's a work around.

**Comment by carlosbustillordguez** [comment]
Any update about this issue? This is a problem in some GitHub pipelines because some runners use AZ CLI v2.41.0 (fails here) and others v2.40.0 (works here).

**Comment by PramodValavala-MSFT** [comment]
@alan-marcinkowski There is some progress in #24185 which was created earlier. We are working on getting a fix out for this soon.

**Comment by alan-marcinkowski** [comment]
> @alan-marcinkowski There is some progress in #24185 which was created earlier. We are working on getting a fix out for this soon.

...Yes, I'm following it there actually. As mentioned, it's not an issue for us as we were able to downgrade our ADO agent pool. Thanks.

**Comment by PramodValavala-MSFT** [comment]
@alan-marcinkowski Sorry about that. Meant to mention @carlosbustillordguez instead. 😅

**Comment by LyndonP** [comment]
> > @alan-marcinkowski There is some progress in #24185 which was created earlier. We are working on getting a fix out for this soon.
> 
> ...Yes, I'm following it there actually. As mentioned, it's not an issue for us as we were able to downgrade our ADO agent pool. Thanks.

@alan-marcinkowski Where do you 'downgrade' your ADO agent pool? (want to see if this is something I can try on my end)

**Comment by alan-marcinkowski** [comment]
We have

> > > @alan-marcinkowski There is some progress in #24185 which was created earlier. We are working on getting a fix out for this soon.
> > 
> > 
> > ...Yes, I'm following it there actually. As mentioned, it's not an issue for us as we were able to downgrade our ADO agent pool. Thanks.
> 
> @alan-marcinkowski Where do you 'downgrade' your ADO agent pool? (want to see if this is something I can try on my end)

We have an Azure VMSS used and an ADO agent pool. We use the CustomScript extension to setup the agents in that pool. In that custom script, we used to always install latest / head Azure CLI in that script ... but  now we install a specific (downgraded) version of Azure CLI.
