### ISSUE TITLE
"az aks create" fails with "progress_patch() got an unexpected keyword argument 'det'". 

### ISSUE THREAD

**Issue by MilanMasek** [Azure/azure-cli#17740]
When using az interactive extension, error is thrown as shown below. Cluster gets created and seems to be working. However, it is not clear that the operation is completed successfully.
Same error happens, when I do "az>> aks stop --name {} -g {}". Perhaps same for a group of aks commands.

## Describe the bug

**Command Name**
`Unknown (aks create  ...) `

**Errors:**
```
progress_patch() got an unexpected keyword argument 'det'
Traceback (most recent call last):
cliextensions/interactive/azext_interactive/azclishell/app.py, ln 663, in cli_execute
    result = invocation.execute(args)
azure/cli/core/commands/__init__.py, ln 657, in execute
    raise ex
azure/cli/core/commands/__init__.py, ln 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
azure/cli/core/commands/__init__.py, ln 702, in _run_job
    result = LongRunningOperation(cmd_copy.cli_ctx, 'Starting {}'.format(cmd_copy.name))(result)
azure/cli/core/commands/__init__.py, ln 878, in __init__
    self.progress_bar = progress_bar if progress_bar is not None else IndeterminateProgressBar(cli_ctx)
azure/cli/core/commands/progress.py, ln 186, in __init__
    hide_cursor=False))
TypeError: progress_patch() got an unexpected keyword argument 'det'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks create -g {} -n {} --ssh-key-value {} --node-count {}`

## Environment Summary
```
Linux-4.15.0-54-generic-x86_64-with-debian-buster-sid
Python 3.6.10
Installer: DEB

azure-cli 2.22.0

Extensions:
interactive 0.4.4

```

**Comment by yungezz** [comment]
route to appropriate team

**Comment by jiasli** [comment]
This issue was introduced by PR #17262 and got released since `azure-cli-2.22.0`. 

In e536c7e17ca1696a2cd69940df339c128840ed21, `det` is passed to `get_progress_controller` as **keyword** argument:

https://github.com/Azure/azure-cli/blob/e536c7e17ca1696a2cd69940df339c128840ed21/src/azure-cli-core/azure/cli/core/commands/progress.py#L181-L182

In `azext_interactive`, `get_progress_controller` is patched as `progress_patch`:

https://github.com/Azure/azure-cli-extensions/blob/f7f9ca9c1cafeddd3d3f6e2087530c64334e3027/src/interactive/azext_interactive/azclishell/app.py#L690

```py
        self.cli_ctx.get_progress_controller = self.progress_patch
```

but `progress_patch` doesn't take keyword argument `det`:

https://github.com/Azure/azure-cli-extensions/blob/f7f9ca9c1cafeddd3d3f6e2087530c64334e3027/src/interactive/azext_interactive/azclishell/app.py#L680-L684

```py
    def progress_patch(self, _=False):
        """ forces to use the Shell Progress """
        from .progress import ShellProgressView
        self.cli_ctx.progress_controller.init_progress(ShellProgressView())
        return self.cli_ctx.progress_controller
```

This causes the failure.

**Comment by ozbillwang** [comment]
yes, got same issue after upgrade to latest

```
az>> az version
{
  "azure-cli": "2.24.2",
  "azure-cli-core": "2.24.2",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "azure-devops": "0.18.0",
    "blueprint": "0.3.0",
    "interactive": "0.4.4"
  }
}

az>> az vm image list-skus --location australiasoutheast --publisher OpenLogic --offer CentOS |jq .[].name|grep "\"7"
Error loading command module 'iot': progress_patch() got an unexpected keyword argument 'det'
Error loading command module 'network': progress_patch() got an unexpected keyword argument 'det'
Error loading command module 'resource': progress_patch() got an unexpected keyword argument 'det'
Error loading command module 'sql': progress_patch() got an unexpected keyword argument 'det'
Error loading command module 'vm': progress_patch() got an unexpected keyword argument 'det'
'vm' is misspelled or not recognized by the system.
```
I tried other sub-commands, similar issues.

But `az account show` has no issue.

My old version is `2.21.0`, work for a while without any issue (more than half year). If others report the problem on version 2.23.0, then the problem is in the changed codes between these versions. 

### update 1 with work around

I am Macbook user, but `brew install` can only install the latest `azure-cli`, so I get it back with old version by below commands

```
brew uninstall azure-cli
pip install azure-cli==2.21.0
```
after rollback to version 2.21.0, everything works as usual.

### Update 2

This issue is duplicated on version `2.22.0`, looks like a hard job to find out which one made the trouble.

```
$ git rev-list --ancestry-path azure-cli-2.21.0..azure-cli-2.22.0
a4582a388033dde268fad640656acfe1a5781a64
039fa21db4fdf6dfb22958aaf1c3f614e1fc3b59
a3604d1f872b3671e2bb17948a47f0e7be5dbb07
6c81f0d5627b05ff3ad849dc18e9233810fc334d
3b813cb6b68cba722f52baf2bac1797a0a270847
6887d372eccadd97193e18966ec1f68139c38ae5
0a52e8f0dc91f7faf45822df826758948e056593
711cbca5d58513e503a39950f7e0fba4d5353031
69b17f246e056c16017acc653b631cb224bb407d
a9e5c85208d36ba4d9fdca55051020abe4ea8edd
119856d4f5984e5a4ef0cdb5bc233c6f07da2720
2243e74d8924e9b050e789682c450f8700e9caed
2fcf0b0517acc5b30f69c4faff9a660d660f3bc8
2cef51d61bcd75cf21ad713e8a6631a25a0477f8
ad15b453ac3ded5fb95e1d0e66ee0e427d3a4cfd
5544a0f3bc32aa778d296f71c4d37e48f8ebe691
116bdd5cda7c9368d25c5b4d3169996a7682e338
4b7980cd1aa55aab4a7c7ef2dcb2d387896b1d96
532f4ca4699fc3dc422d2b521f636bf24ffeee0a
d2e77ca8300fe79ad3122934e0fc21d2163abab2
c808ba40b95235a5216fa42e91f4937c085b53cf
e695a0167f57199065c9d92e266008d18967b5da
c18dc184085029faec2d94386a911af8b0be6e35
9191211ddc14e5a83cd5292a9fad78b0f8741b54
93f45fb7b3a2d186ab07101edd894fe4d156b202
753a11c87575fedcc7425d4e34d332b17d8cd17b
8aa6d1819484f1cc96a5b89a5d0d8372eb2bc1ee
6225ca58fd0c783a6b9be45c7b7679b2f8bb90c5
12be82276788bc1fd314aa712642b9655a766a6c
cbd54d519ada70e45fd379aed259eca98af91ad7
bf08c94d8f0237a137cce72bddda0f21e45b784e
9c8554cedb038b14a3bbca015d29dcdc0d6488cb
64847ce9c2c12ce8d0d8e4df534b70a29761dfd4
07595c1ced2704a084ee3aaac9c04c93cfb05b64
29767d75d850ddc1c24cc85bd46d861b61d77a47
7ec9e7ca8ad470112579a75158d356ba80c68174
b08a6b49bcef6170386d44a050dcea8f481fe6c0
885be54cb7ec475b3da1eff59bde7a08fb5203c0
85d73f38efbfbf41c0113ebdffc5ec555d603d1e
dd351466bb124d3cdb1e087610f626d917cb7721
4eabb550d4b21b4ace999279a31c5b83b802068f
ad30d5595a4e49ff4fa5b2be887b8fac3a1bce79
fd4780157205f240081d783394d96077caf44620
7b68db9ae46d8c552aa50eb20857c06a7b21b84a
acd463307edc735b23a3d20fddf2a997f6d746f4
0fa1fb5974c8c7ffcd4dd5d1f34fa4da8aadc602
86037fb7edb9b4a7986c03d03ecd7ad2599f2efc
4fffb690f5a5252b0260cdd916b0b7ce5c381808
57f33f0b60f4b7c5379208c4a13e239d0949c735
db4c326ef38c394e31f492b1e026aecb925c63a8
bbf753f73be34f8725bfa36a962db04524a73985
b457d862fea353f59377e5beb7c2b043e90019ed
e536c7e17ca1696a2cd69940df339c128840ed21
39f2968af61945d4580472288cf388b1098ed920
7a5538f0d062f3fde2950dc3f310735807ec7bd4
44e1af8768f0365601014f6aa7f411abe990623b
f331b036790b9df81ae0b8374479535df9537dab
0194d3b3d33fd6e30d08d5b9a5fbc6d0e58807ee
8828c74f1453681f50784335a526eb39b511ee50
ad284d0fb6516104d4f1dca887caf166d72a8404
3bff786b9e337aa35bb4cc64a09e5600a35663f8
984e06a65a40bcc2cc0c008c1b7bb4eff4799c8a
eb08437b9bcf71598226ab4dfe4a605fda063126
19073d69d98761d44c5c88e76f551a52fa630c2a
212f925303aa0a5e2fe5784488b558519040d810
0bfe544055383596f629c8e62572b3e537e5a642
490cafb56859312baae6a7c0e3d936429329bfe3
23facb0f986ccb8025d672842b6b53c7e58b282c
f8216901b9b539540491f3fa25eba4920bc3d6ae
d727390470fe4bd3961acd8c4258179065b4ceaa
fb1fb85ca738476b3bf46af50d5bfb798f1c5c57
962f0ca7f02ed15903d5ec169dd298e80f654544
f721fd35d8ab45526b110986c4a1a5203eb722b0
983cb41d4cfce51fd07e7e0244a6383af35dd265
357805aad1a8ea2f02ef27d56218279d9bbab38b
0df58e9ab2e4c4e0986f2bb8ce4fa0e02c2b4bff
0097fa36db753a52b80881cee593ff8473f868ed
50ccb24528eb36529d1432808f3ff385cc4c04aa
2b8624186b4c970da4514ee6ed13ee9f6415781c
4f0fe51956e9ddb7d632b084a2315f09d712a14f
f0412f74fc14144059f974b9c5f0176628861ef3
8fa70cffbe4dcf70b12cc756d61118f653697420
12a91582aee11201edf176b26e07b7ccfaa0200e
45d53d38671098ae5415761c03a568ad25d3e67e
fb2d98f7c305b6eefec8a1c0fc472bc8f8ea4d6f
e6e8f8a2fd19c356a569ccd900e9bf9acf4779f9
```

**Comment by SunChero** [comment]
i have the same issue with the latest az version
 ```az version
{
  "azure-cli": "2.38.0",
  "azure-cli-core": "2.38.0",    
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "azure-devops": "0.25.0",    
    "eventgrid": "0.4.9",        
    "interactive": "0.4.5",      
    "log-analytics": "0.2.2"     
  }
}
```
many commands are not working ...
```
az>> az group list -o table
Error loading command module 'iot': AzInteractiveShell.progress_patch() got an unexpected keyword argument 'det'
Error loading command module 'network': AzInteractiveShell.progress_patch() got an unexpected keyword argument 'det'
Error loading command module 'resource': AzInteractiveShell.progress_patch() got an unexpected keyword argument 'det'
Error loading command module 'sql': AzInteractiveShell.progress_patch() got an unexpected keyword argument 'det'
Error loading command module 'vm': AzInteractiveShell.progress_patch() got an unexpected keyword argument 'det'
'group' is misspelled or not recognized by the system.

Examples from AI knowledge base:
https://aka.ms/cli_ref
Read more about the command in reference docs
az>> ````
