### PR TITLE
Fix #1022: Document CI is Broken

### LINKED ISSUE #1022: Document CI is broken
It is broken at https://ci.appveyor.com/project/VisualStudioChinaAppVeyorUsers/azure-cli/build/1.0.200 with commit https://github.com/Azure/azure-cli/commit/90c7b7de3159e41160c96dbaffd13f94e20c3874.

Errors:
Exception occurred:
  File "C:\projects\azure-cli\doc\sphinx\azhelpgen\azhelpgen.py", line 51, in <lambda>
    + str(not p.required) + p.name):
AttributeError: module 'azure.cli.core._help' has no attribute 'get_group_priority'

### PR DESCRIPTION
**Pull request by formulahendry**
#1022 It is broken in commit https://github.com/Azure/azure-cli/commit/90c7b7de3159e41160c96dbaffd13f94e20c3874 because get_group_priority has changed in _help.py but not in azhelpgen.py

### CODE REVIEW

**Comment by mayurid** [comment]
@tjprescott and @derekbekoe to look
Looks good from my side.
