### PR TITLE
[App Service] Fix #18151: `az webapp config backup restore`: Fix the bug that 'WebAppsOperations' object has no attribute 'restore_slot'

### LINKED ISSUE #18151: webapp: Unable to run restore command
In our devops pipeline we do a restore of an backup, with this command
`az webapp config backup restore --slot $(targetSlot) --target-name $WebAppName-$(targetSlot) --overwrite --resource-group $(WebAppResourceGroup) --webapp-name $WebAppName --backup-name $WebAppName --container-url $sas`

but since the upgrade of azurecli to 2.23 we get this error..
```
2021-05-19T06:56:19.6626484Z azure-cli                         2.23.0
2021-05-19T06:56:21.8583491Z [command]C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\azureclitaskscript1621407378735.ps1'"
2021-05-19T06:56:28.5408959Z ERROR: The command failed with an unexpected error. Here is the traceback:
2021-05-19T06:56:28.5412273Z ERROR: 'WebAppsOperations' object has no attribute 'restore_slot'
```

with 2.21 it ran fine.
```
2021-04-12T13:34:07.1548494Z azure-cli                         2.21.0
2021-04-12T13:34:09.7851601Z [command]C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\azureclitaskscript1618234446120.ps1'"
2021-04-12T13:39:53.3416446Z [command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" account clear"
```

We can see that there is a breaking change in 2.23
[BREAKING CHANGE] Update websites SDK to the latest version (azure-mgmt-web==2.0.0) & Adopt track2 SDK
But checking the [documentation](https://docs.microsoft.com/en-us/cli/azure/webapp/config/backup?view=azure-cli-latest#az_webapp_config_backup_restore) for backup the command still seems valid but doesnt work.

### PR DESCRIPTION
**Pull request by skotz**
Fixes issue #18151 where restoring a backup to a slot would fail for the following reason: `'WebAppsOperations' object has no attribute 'restore_slot'`.

**Related command**

az webapp config backup restore

**Description**

Changing the method from `restore_slot` (which doesn't appear to be a valid method) to [begin_restore_slot](https://docs.microsoft.com/en-us/python/api/azure-mgmt-web/azure.mgmt.web.v2021_02_01.operations.webappsoperations?view=azure-python#azure-mgmt-web-v2021-02-01-operations-webappsoperations-begin-restore-slot) fixes the issue for me. The `restore` method was also updated to `begin_restore` and tested.

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
App Service

**Comment by zhoxing-ms** [comment]
Could you add some tests for these case?

**Comment by skotz** [comment]
@zhoxing-ms Added tests

**Review by zhoxing-ms — APPROVED** [review]
