### ISSUE TITLE
Az Container Create Returning Error: " 'ResourcesOperations' object has no attribute 'create_or_update' "

### ISSUE THREAD

**Issue by GulsahG** [Azure/azure-cli#18291]
## Describe the bug

**Command Name**
`az container create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'ResourcesOperations' object has no attribute 'create_or_update'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/container/custom.py", line 113, in create_container
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/container/custom.py", line 407, in _create_update_from_file
AttributeError: 'ResourcesOperations' object has no attribute 'create_or_update'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az container create --resource-group {} --file {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.24.0

```
## Additional Context

Here's my YAML file.

```
apiVersion: 2019-12-01
location: westeurope
name: nmsContainerGroup
properties:
  containers:
  - name: aci-rtmp-app
    properties:
      environmentVariables:
        - name: 'SECRET_KEY'
          secureValue: <secret_key>
      image: <docker_image_name>
      resources:
        requests:
          cpu: 1
          memoryInGb: 1.5
      volumeMounts:
      - mountPath: ./media/
        name: filesharevolume
      ports:
      - port: 8080
  osType: Linux
  restartPolicy: Always
  ipAddress:
    type: Public
    ports:
    - protocol: tcp
      port: 8080
  volumes:
  - name: filesharevolume
    azureFile:
      sharename: acishare
      storageAccountName: rtmpstorage328
      storageAccountKey: <storage_key>
tags: null
type: Microsoft.ContainerInstance/containerGroups
```

**Comment by yonzhan** [comment]
route to service team

**Comment by s2terminal** [comment]
I tried to create a container instance using yaml as described in the official documentation below. Then I got the same `'ResourcesOperations' object has no attribute 'create_or_update'` error.

https://docs.microsoft.com/en-us/azure/container-instances/container-instances-multi-container-yaml

**Comment by PatrickVibild** [comment]
I can confirm. Same issue. Spotted on Azure pipeline when running CLI ver: 2.24. 

I could create containers locally with a CLI ver: 2.22, after updating to 2.24 I had same issues as shown in the pipeline.

Issue is generated at line [407](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/container/custom.py) 

ResourceOperations is missing create_or_update attribute. Could not track changes that created this issue.

**Comment by gpatkos** [comment]
I experience the same error. It still worked a few days ago, not now. It would be very important to fix this bug because it is blocking our development!

**Comment by atmaxinger** [comment]
This is also a blocking issue for us.

**Comment by k2703** [comment]
This is also a blocking issue for us.

**Comment by yonzhan** [comment]
container instance service team should look into this

**Comment by dunlopkr** [comment]
This is affecting numerous teams across my organization.

**Comment by dunlopkr** [comment]
I have been able to work around this issue by using and Ubuntu hosted agent and switch the Script Type property in all the Azure CLI tasks from “PowerShell” to “PowerShell Core" . I believe it works because the Ubuntu hosted agents have not been update to azure-cli 2.24 and are still using azure-cli 2.23. I am concerned that the effort to switch all pipelines to Ubuntu will only be a temporary fix. I suspect when the Ubuntu hosted agents are updated to use azure-cli 2.24 that we will start to see this failure again.  Switching to Ubuntu may not be possible in all scenarios so a real fix is needed ASAP.

**Comment by jiasli** [comment]
Duplicate of #18276

**Comment by yonzhan** [comment]
Add @zhoxing-ms to help with

**Comment by jcescala** [comment]
Issue also on macOS for both 2.24.0 and 2.24.1 versions on AZ CLI
