### ISSUE TITLE
az aks get-credentials broken in 2.0.24

### ISSUE THREAD

**Issue by torosent** [Azure/azure-cli#5299]
---

### Environment summary

Using Mac with az 2.0.24 via Homebrew ``` az aks get-credentials``` is broken
Works ok on 2.0.23

```
az aks get-credentials --name playground --resource-group playground
```

Output 
```
'ManagedCluster' object has no attribute 'properties'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.24_1/libexec/lib/python3.6/site-packages/knack/cli.py", line 193, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.24_1/libexec/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 319, in execute
    six.reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.0.24_1/libexec/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.0.24_1/libexec/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 292, in execute
    result = cmd(params)
  File "/usr/local/Cellar/azure-cli/2.0.24_1/libexec/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 169, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.24_1/libexec/lib/python3.6/site-packages/knack/commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.24_1/libexec/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 328, in default_command_handler
    result = op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.0.24_1/libexec/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 1329, in aks_get_credentials
    access_profiles = mc.properties.access_profiles
AttributeError: 'ManagedCluster' object has no attribute 'properties'
```

**Comment by kvolkovich-sc** [comment]
It works ok with 2.0.23

To `azure-cli` development team: Can you please provide homebrew formulas for previous versions. Now I can install the only latest version of `azure-cli` using brew.

**Comment by tjprescott** [comment]
Dupe of: https://github.com/Azure/azure-cli/issues/5276

This has already been fixed and will be in the 2.0.25 release.  In the meantime, you could get the edge build to have that fix now.
https://github.com/Azure/azure-cli#edge-builds

@derekbekoe for the Homebrew question.

**Comment by derekbekoe** [comment]
This should help
https://github.com/Azure/azure-cli/issues/5218#issuecomment-357928066
