### ISSUE TITLE
az servicebus topic create --max-size fail

### ISSUE THREAD

**Issue by onybo** [Azure/azure-cli#9697]
Can't set max-size on a topic using the command:
`az servicebus topic create -n mytopic -g myrg --namespace-name mynamespace  --max-size 1024`

Have tried sizes: 1024, 2048, 3072, 4096, 5120.
Same command is working fine in windows using version 2.0.46 of the CLI. Was also working fine on my mac until I upgraded today using homebrew, not sure what version I had before I upgraded.
I version 2.0.66 I can no longer use the --max-size switch.

## Describe the bug

**Command Name**
`az servicebus topic create`

**Errors:**
```
get() missing 1 required positional argument: 'topic_name'
Traceback (most recent call last):
python3.7/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 560, in execute
    raise ex
cli/core/commands/__init__.py, ln 618, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 611, in _run_job
    six.reraise(*sys.exc_info())
...
cli/core/commands/__init__.py, ln 297, in __call__
    return self.handler(*args, **kwargs)
azure/cli/core/__init__.py, ln 461, in default_command_handler
    return op(**command_args)
cli/command_modules/servicebus/custom.py, ln 188, in cli_sbtopic_create
    getnamespace = client.get(resource_group_name=resource_group_name, namespace_name=namespace_name)
TypeError: get() missing 1 required positional argument: 'topic_name'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az servicebus topic create --name {} -g {} --namespace-name {} --max-size {}`

## Environment Summary
```
Darwin-18.6.0-x86_64-i386-64bit
Python 3.7.3
Shell: bash

azure-cli 2.0.66

```

**Comment by tjprescott** [comment]
@v-Ajnava for action

**Comment by v-Ajnava** [comment]
@onybo can you please try with latest CLI release 2.0.67 and let us know if you face  any issues. 
I was able to create topic with --max-size with CLI 2.0.67.

**Comment by onybo** [comment]
@v-Ajnava I have now tried with version 2.0.67 and it now seems to work as expected.
Thanks
