### ISSUE TITLE
az redis firewall-rules throwing an exception

### ISSUE THREAD

**Issue by mccleanp** [Azure/azure-cli#18950]
```
az redis firewall-rules
The command failed with an unexpected error. Here is the traceback:
The operation 'azure.mgmt.redis.operations#FirewallRulesOperations.list_by_redis_resource' is invalid.
Traceback (most recent call last):                                                                                                                                                           
  File "/home/paul/Code/frp/az-cli/.azdev/azdev-env/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 61, in get_op_handler                                    
    handler = getattr(handler, part)                                                                                                                                                         
AttributeError: type object 'FirewallRulesOperations' has no attribute 'list_by_redis_resource'
```

Looks like the azure_mgmt_redis module has been updated, which removed the list_by_redis_resource method.

**Comment by yonzhan** [comment]
route to service team

**Comment by m1kola** [comment]
Hey. Any idea when we should expect the fix? Or what would be a workaround for `azdev` users?

In [Azure/ARO-RP](https://github.com/Azure/ARO-RP) we use `azdev` in CI which installs `azure-cli` which in turn is not pinned to a specific version, so this breaks our CI. Any advice would be appreciated.

**Comment by m1kola** [comment]
It looks like this issue was fixed somewhere between today and 2nd of August.

**Comment by jjaguirre394** [comment]
> It looks like this issue was fixed somewhere between today and 2nd of August.

@m1kola So this issue will be closed and the fix included in the next release?

**Comment by jjaguirre394** [comment]
Can anyone who works on this area confirm if this fix is included in the latest release (2.27.1)? If so, this issue can be closed?

**Comment by jjaguirre394** [comment]
Looks like it is working in version 2.27.1 for me, but I need to tie my investigation back to this issue being closed in order to proceed. Any response on this would be much appreciated.

**Comment by jjaguirre394** [comment]
Hi @yonzhan any update on this?

**Comment by yonzhan** [comment]
redis service team should look into this
