### ISSUE TITLE
WebApp:az webapp up crash after upgrade to v2.30

### ISSUE THREAD

**Issue by lucafaggianelli** [Azure/azure-cli#20230]
## Describe the bug

**Command Name**
`az webapp up`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'CLIError' object has no attribute 'response'
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.30.0/libexec/lib/python3.9/site-packages/azure/cli/command_modules/appservice/custom.py", line 3843, in webapp_up
    create_app_service_plan(cmd, rg_name, plan, _is_linux, hyper_v=False, per_site_scaling=False, sku=sku,
  File "/opt/homebrew/Cellar/azure-cli/2.30.0/libexec/lib/python3.9/site-packages/azure/cli/command_modules/appservice/custom.py", line 1685, in create_app_service_plan
    _validate_asp_sku(app_service_environment, sku)
  File "/opt/homebrew/Cellar/azure-cli/2.30.0/libexec/lib/python3.9/site-packages/azure/cli/command_modules/appservice/custom.py", line 4354, in _validate_asp_sku
    raise CLIError("Only pricing tier 'Isolated' is allowed in this app service plan. Use this link to "
knack.util.CLIError: Only pricing tier 'Isolated' is allowed in this app service plan. Use this link to learn more: https://docs.microsoft.com/azure/app-service/overview-hosting-plans

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.30.0/libexec/lib/python3.9/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.30.0/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.30.0/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.30.0/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 712, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/opt/homebrew/Cellar/azure-cli/2.30.0/libexec/lib/python3.9/site-packages/azure/cli/command_modules/appservice/commands.py", line 37, in _ex_handler
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.30.0/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/Cellar/azure-cli/2.30.0/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.30.0/libexec/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/homebrew/Cellar/azure-cli/2.30.0/libexec/lib/python3.9/site-packages/azure/cli/command_modules/appservice/custom.py", line 3847, in webapp_up
    if ex.response.status_code == 409:  # catch 409 conflict when trying to create existing ASP in diff location
AttributeError: 'CLIError' object has no attribute 'response'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp up --resource-group {} --name {} --subscription {} --plan {} -e {} --runtime {}`

## Environment Summary
```
macOS-12.0.1-arm64-arm-64bit, Darwin 21.1.0
Python 3.9.7
Installer: HOMEBREW

azure-cli 2.30.0

```

**Comment by yonzhan** [comment]
route to service team

**Comment by Kotasudhakarreddy** [comment]
@lucafaggianelli did you try again with the new `AppService plan` name.

**Comment by panchagnula** [comment]
@lucafaggianelli do you still repro this with the latest version of CLI?

**Comment by lucafaggianelli** [comment]
At the end I'm not using the CLI for the deployment anymore but I'm deploying from an Azure DevOps pipeline and it works.
On top of that issue I also had a problem with the proxy, as my App Service instance is inside an Isolated ASP and apparently the az CLI doesn't like that, so at the end the DevOps pipeline is working fine.

**Comment by panchagnula** [comment]
> At the end I'm not using the CLI for the deployment anymore but I'm deploying from an Azure DevOps pipeline and it works.
> On top of that issue I also had a problem with the proxy, as my App Service instance is inside an Isolated ASP and apparently the az CLI doesn't like that, so at the end the DevOps pipeline is working fine.

@lucafaggianelli az webapp up is not support for ILBASE - you can use az webapp create, az webapp deployment config zip  or ASE commands under az AppService , which is similar to using devops pipeline directly. @StrawnSC with up enable for ASE V3 only - we need add better exceptional handling & validations to call out when something is not supported, instead of crashing.

**Comment by lucafaggianelli** [comment]
Ah here we go, OK good to know!

**Comment by StrawnSC** [comment]
@panchagnula it looks like the ASE error handling is a little messed up. For some reason, the CLI buried the original error:
`knack.util.CLIError: Only pricing tier 'Isolated' is allowed in this app service plan. Use this link to learn more: https://docs.microsoft.com/azure/app-service/overview-hosting-plans`

This is also happening in the case of https://github.com/Azure/azure-cli/issues/21080

I'll make the following changes to the way `az webapp up` handles ASEs: 
- Fix the error handling to surface the correct error 
- Validate that the ASE passed in is both an ASEV3 and not and ILB ASE 
- If no SKU is provided (and the user is using an ASE) default to the `I1V2` ASE
- If a user passes in an ASE and an ASP that already exists (via `--plan`), validate that the ASP is in the ASE and don't attempt to create a new ASP
