### ISSUE TITLE
cannot import name 'BatchManagementClient' from 'azure.mgmt.batch' (/usr/lib/python3/dist-packages/azure/mgmt/batch/__init__.py)

### ISSUE THREAD

**Issue by chris-lindbergh-uplight-com** [Azure/azure-cli#16568]
## Describe the bug

When running the command below, I previously would get a list of IP addresses.  Now I get the error attached.  Other "az" commands like "az account list" work without error.  Tried purging and installing the "azure-cli" package - no help.

**Command Name**
`az network public-ip list`

**Errors:**
```
cannot import name 'BatchManagementClient' from 'azure.mgmt.batch' (/usr/lib/python3/dist-packages/azure/mgmt/batch/__init__.py)
Traceback (most recent call last):
python3/dist-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 558, in execute
    self.commands_loader.load_arguments(command)
...
network/private_link_resource_and_endpoint_connections/resource_providers/batch_provider.py, ln 6, in <module>
    from azure.mgmt.batch import BatchManagementClient
ImportError: cannot import name 'BatchManagementClient' from 'azure.mgmt.batch' (/usr/lib/python3/dist-packages/azure/mgmt/batch/__init__.py)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network public-ip list --out {}`

## Expected Behavior

A list of IP addresses

## Environment Summary
```
Linux-5.10.0-1-amd64-x86_64-with-glibc2.31
Python 3.9.1+
Installer: PIP

azure-cli 2.17.1

Extensions:
azure-devops 0.19.0

```

**Comment by chris-lindbergh-uplight-com** [comment]
Other "az network" commands return a similar error instead of expected output.

**Comment by yonzhan** [comment]
network

**Comment by chris-lindbergh-uplight-com** [comment]
Upgraded to 2.18.0 and the `az network` commands now work.

**Comment by dialogbox** [comment]
I got the same error even with the 2.18.0.

```
az version
{
  "azure-cli": "2.18.0",
  "azure-cli-core": "2.18.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "azure-devops": "0.19.0"
  }
}
```

**Comment by yonzhan** [comment]
@kairu-ms for awareness

**Comment by dialogbox** [comment]
It works with 2.30.0 but I used a different machine for the new version because of a security policy applied to the original workstation. Not sure which one solved my issue, using a different machine or using a newer version.
