### ISSUE TITLE
az container logs is broken in 2.28.0

### ISSUE THREAD

**Issue by ghelyar** [Azure/azure-cli#19558]
**Describe the bug**
Azure CLI breaks az container logs in 2.28.0. It was working in 2.27.2.

```
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: 'ContainerInstanceManagementClient' object has no attribute 'container'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 112, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/container/_client_factory.py", line 18, in cf_container
AttributeError: 'ContainerInstanceManagementClient' object has no attribute 'container'
```

**To Reproduce**
```
az container logs --name ... --resource-group ...
```

**Expected behavior**
Container logs are output

**Environment summary**
Azure DevOps build agent (Windows Server 2019)

**Comment by yonzhan** [comment]
route to service team

**Comment by kf6kjg** [comment]
Probably the same underlying problem and workarounds as #19489

**Comment by PramodValavala-MSFT** [comment]
@ghelyar Looks like this has since been fixed and I can confirm that there is no error now. Apologies for no updates on this issue sooner. Unless you are still seeing this error on your end with the latest version, I believe this could be closed.
