### ISSUE TITLE
az synapse workspace-package upload fails due to missing positional argument

### ISSUE THREAD

**Issue by CribberSix** [Azure/azure-cli#24738]
**Related command**
az synapse workspace-package upload

**Error**
`LibraryOperations.append() missing 1 required positional argument: 'content'`
See full trace below.

**Describe the bug**
The command fails in the DevOps Powershell script and .whl files are uploaded with "incomplete" provisioning status to the Synapse workspace.

**To Reproduce**
DevOps Pipeline with 2 "download package" tasks and an Azure CLI task containing the following inline script: 

```sh
# CONFIG - variables retrieved from Azure release pipeline parameters
$workspace_name = $(synapse_workspace_name)

# Get downloaded packages by name
$file_names = Get-ChildItem *.whl

foreach ($file_name in $file_names.name) {
az synapse workspace-package upload --workspace-name $workspace_name --package $file_name
}
```

**Expected behavior**
.whl Files successfully uploaded to the Synapse workspace.

**Environment summary**
- DevOps Task: Azure CLI - Task Version 2.*
- Powershell Script, inline-script
- azure-cli: `2.42.0`
- core: `2.42.0`
- telemetry `1.0.8`
- azure-devops: `0.25.0`

**Additional context**
Operation ran smoothly until yesterday evening when the error started to occur throughout all of our environments and Synapse workspaces. Seems like an update happened? 

I think it is a bug introduced in `azure-cli=2.42.0` or `core=2.42.0`, I just checked our logs from before and it worked with `azure-cli=2.41.0` and `core=2.41.0`.

**Error log**
```
2022-11-25T07:06:42.5074817Z WARNING: Command group 'synapse' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
2022-11-25T07:06:53.2147015Z ERROR: The command failed with an unexpected error. Here is the traceback:
2022-11-25T07:06:53.2151567Z ERROR: LibraryOperations.append() missing 1 required positional argument: 'content'
2022-11-25T07:06:53.2152312Z Traceback (most recent call last):
2022-11-25T07:06:53.2153019Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
2022-11-25T07:06:53.2153908Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
2022-11-25T07:06:53.2154623Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
2022-11-25T07:06:53.2155316Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
2022-11-25T07:06:53.2155990Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
2022-11-25T07:06:53.2156661Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
2022-11-25T07:06:53.2157401Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/synapse/manual/operations/artifacts.py", line 397, in upload_workspace_package
2022-11-25T07:06:53.2158148Z   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/tracing/decorator.py", line 73, in wrapper_use_tracer
2022-11-25T07:06:53.2158734Z TypeError: LibraryOperations.append() missing 1 required positional argument: 'content'
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@CribberSix Thank you for reaching out, we are looking into it.

**Comment by RakeshMohanMSFT** [comment]
This is duplicate of https://github.com/Azure/azure-cli/issues/24718 we will track this issue in #24718
