### ISSUE TITLE
az cli 2.25.0 fails at login while running python script from az cli task in azure DevOps

### ISSUE THREAD

**Issue by sugamg** [Azure/azure-cli#18532]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
azure cli task in Azure DevOps fails while running python script for training and registering an ML model. 
This started happening when 2.25.0 was released.
pipelines work just fine on 2.24.2, we rolled back and tested with 2.24.2 version.

 **Error**
 2021-06-15T18:01:14.8540971Z azure-cli                         2.25.0
2021-06-15T18:01:14.8541649Z 
2021-06-15T18:01:14.8542216Z core                              2.25.0
2021-06-15T18:01:14.8542901Z telemetry                          1.0.6
2021-06-15T18:01:14.8543999Z 
2021-06-15T18:01:14.8545458Z Extensions:
2021-06-15T18:01:14.8546320Z azure-devops                      0.18.0
2021-06-15T18:01:14.8546777Z 
2021-06-15T18:01:14.8547398Z Python location 'C:\hostedtoolcache\windows\Python\3.7.9\x64\python.exe'
2021-06-15T18:01:14.8548306Z Extensions directory 'C:\Program Files\Common Files\AzureCliExtensionDirectory'
2021-06-15T18:01:14.8548684Z 
2021-06-15T18:01:14.8549716Z Python (Windows) 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
2021-06-15T18:01:14.8550362Z 
2021-06-15T18:01:14.8550934Z Legal docs and information: aka.ms/AzureCliLegal
2021-06-15T18:01:14.8551194Z 
2021-06-15T18:01:14.8551361Z 
2021-06-15T18:01:14.8552040Z Your CLI is up-to-date.
2021-06-15T18:01:14.8553438Z ##[debug]useGlobalConfig=false
2021-06-15T18:01:14.8555763Z ##[debug]Agent.TempDirectory=D:\a\_temp
2021-06-15T18:01:14.8557659Z ##[debug]Agent.TempDirectory=D:\a\_temp
2021-06-15T18:01:14.8566484Z Setting AZURE_CONFIG_DIR env variable to: D:\a\_temp\.azclitask
2021-06-15T18:01:14.8571657Z ##[debug]connectedServiceNameARM=73e16d09-c671-41c9-a2a0-8b9ecd727f27
2021-06-15T18:01:14.8572972Z ##[debug]73e16d09-c671-41c9-a2a0-8b9ecd727f27 data environment = AzureCloud
2021-06-15T18:01:14.8574020Z Setting active cloud to: AzureCloud
2021-06-15T18:01:14.8574866Z ##[debug]which 'az'
2021-06-15T18:01:14.8585724Z ##[debug]found: 'C:\hostedtoolcache\windows\Python\3.7.9\x64\Scripts\az.bat'
2021-06-15T18:01:14.8587198Z ##[debug]C:\hostedtoolcache\windows\Python\3.7.9\x64\Scripts\az.bat arg: cloud set -n AzureCloud
2021-06-15T18:01:14.8588746Z ##[debug]C:\hostedtoolcache\windows\Python\3.7.9\x64\Scripts\az.bat arg: cloud set -n AzureCloud
2021-06-15T18:01:14.8595838Z ##[debug]exec tool: C:\hostedtoolcache\windows\Python\3.7.9\x64\Scripts\az.bat
2021-06-15T18:01:14.8607166Z ##[debug]exec tool: C:\hostedtoolcache\windows\Python\3.7.9\x64\Scripts\az.bat
2021-06-15T18:01:14.8608375Z ##[debug]arguments:
2021-06-15T18:01:14.8609645Z ##[debug]arguments:
2021-06-15T18:01:14.8610832Z ##[debug]   cloud
2021-06-15T18:01:14.8611622Z ##[debug]   cloud
2021-06-15T18:01:14.8612356Z ##[debug]   set
2021-06-15T18:01:14.8613081Z ##[debug]   set
2021-06-15T18:01:14.8613819Z ##[debug]   -n
2021-06-15T18:01:14.8614545Z ##[debug]   -n
2021-06-15T18:01:14.8615270Z ##[debug]   AzureCloud
2021-06-15T18:01:14.8616214Z ##[debug]   AzureCloud
2021-06-15T18:01:14.8617065Z [command]C:\Windows\system32\cmd.exe /D /S /C "C:\hostedtoolcache\windows\Python\3.7.9\x64\Scripts\az.bat cloud set -n AzureCloud"
2021-06-15T18:01:17.0539349Z ##[debug]connectedServiceNameARM=73e16d09-c671-41c9-a2a0-8b9ecd727f27
2021-06-15T18:01:17.0544442Z ##[debug]73e16d09-c671-41c9-a2a0-8b9ecd727f27 auth scheme = ServicePrincipal
2021-06-15T18:01:17.0545432Z ##[debug]73e16d09-c671-41c9-a2a0-8b9ecd727f27 data SubscriptionID = 2556b6bb-02e2-467c-aede-99902b4e6ae4
2021-06-15T18:01:17.0548657Z ##[debug]73e16d09-c671-41c9-a2a0-8b9ecd727f27 auth param authenticationType = ***
2021-06-15T18:01:17.0550046Z ##[debug]73e16d09-c671-41c9-a2a0-8b9ecd727f27 auth param serviceprincipalid = ***
2021-06-15T18:01:17.0552865Z ##[debug]73e16d09-c671-41c9-a2a0-8b9ecd727f27 auth param tenantid = ***
2021-06-15T18:01:17.0553579Z ##[debug]key based endpoint
2021-06-15T18:01:17.0554897Z ##[debug]73e16d09-c671-41c9-a2a0-8b9ecd727f27 auth param serviceprincipalkey = ***
2021-06-15T18:01:17.0561621Z ##[debug]Processed: ##vso[task.setsecret]***
2021-06-15T18:01:17.0562314Z ##[debug]which 'az'
2021-06-15T18:01:17.0576563Z ##[debug]found: 'C:\hostedtoolcache\windows\Python\3.7.9\x64\Scripts\az.bat'
2021-06-15T18:01:17.0578175Z ##[debug]C:\hostedtoolcache\windows\Python\3.7.9\x64\Scripts\az.bat arg: login --service-principal -u "***" --password=*** --tenant "***" --allow-no-subscriptions
2021-06-15T18:01:17.0579932Z ##[debug]C:\hostedtoolcache\windows\Python\3.7.9\x64\Scripts\az.bat arg: login --service-principal -u "***" --password=*** --tenant "***" --allow-no-subscriptions
2021-06-15T18:01:17.0581185Z ##[debug]exec tool: C:\hostedtoolcache\windows\Python\3.7.9\x64\Scripts\az.bat
2021-06-15T18:01:17.0582179Z ##[debug]exec tool: C:\hostedtoolcache\windows\Python\3.7.9\x64\Scripts\az.bat
2021-06-15T18:01:17.0583251Z ##[debug]arguments:
2021-06-15T18:01:17.0583972Z ##[debug]arguments:
2021-06-15T18:01:17.0584469Z ##[debug]   login
2021-06-15T18:01:17.0584915Z ##[debug]   login
2021-06-15T18:01:17.0585376Z ##[debug]   --service-principal
2021-06-15T18:01:17.0585881Z ##[debug]   --service-principal
2021-06-15T18:01:17.0586336Z ##[debug]   -u
2021-06-15T18:01:17.0586769Z ##[debug]   -u
2021-06-15T18:01:17.0587278Z ##[debug]   ***
2021-06-15T18:01:17.0587795Z ##[debug]   ***
2021-06-15T18:01:17.0588364Z ##[debug]   --password=***
2021-06-15T18:01:17.0588944Z ##[debug]   --password=***
2021-06-15T18:01:17.0589410Z ##[debug]   --tenant
2021-06-15T18:01:17.0590076Z ##[debug]   --tenant
2021-06-15T18:01:17.0590715Z ##[debug]   ***
2021-06-15T18:01:17.0591309Z ##[debug]   ***
2021-06-15T18:01:17.0591779Z ##[debug]   --allow-no-subscriptions
2021-06-15T18:01:17.0592277Z ##[debug]   --allow-no-subscriptions
2021-06-15T18:01:17.0623250Z [command]C:\Windows\system32\cmd.exe /D /S /C "C:\hostedtoolcache\windows\Python\3.7.9\x64\Scripts\az.bat login --service-principal -u *** "--password=***" --tenant *** --allow-no-subscriptions"
2021-06-15T18:01:17.7106474Z ERROR: The command failed with an unexpected error. Here is the traceback:
2021-06-15T18:01:17.7107193Z ERROR: __init__() got an unexpected keyword argument 'user_agent'
2021-06-15T18:01:17.7107721Z Traceback (most recent call last):
2021-06-15T18:01:17.7108580Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\knack\cli.py", line 231, in invoke
2021-06-15T18:01:17.7109242Z     cmd_result = self.invocation.execute(args)
2021-06-15T18:01:17.7109733Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\cli\core\commands\__init__.py", line 657, in execute
2021-06-15T18:01:17.7110159Z     raise ex
2021-06-15T18:01:17.7110630Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\cli\core\commands\__init__.py", line 720, in _run_jobs_serially
2021-06-15T18:01:17.7111147Z     results.append(self._run_job(expanded_arg, cmd_copy))
2021-06-15T18:01:17.7111657Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\cli\core\commands\__init__.py", line 691, in _run_job
2021-06-15T18:01:17.7112313Z     result = cmd_copy(params)
2021-06-15T18:01:17.7112781Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\cli\core\commands\__init__.py", line 328, in __call__
2021-06-15T18:01:17.7113243Z     return self.handler(*args, **kwargs)
2021-06-15T18:01:17.7113705Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\cli\core\commands\command_operation.py", line 121, in handler
2021-06-15T18:01:17.7114167Z     return op(**command_args)
2021-06-15T18:01:17.7114631Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\cli\command_modules\profile\custom.py", line 161, in login
2021-06-15T18:01:17.7115102Z     use_cert_sn_issuer=use_cert_sn_issuer)
2021-06-15T18:01:17.7115573Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\cli\core\_profile.py", line 216, in find_subscriptions_on_login
2021-06-15T18:01:17.7116519Z     username, sp_auth, tenant, self._ad_resource_uri)
2021-06-15T18:01:17.7118169Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\cli\core\_profile.py", line 939, in find_from_service_principal_id
2021-06-15T18:01:17.7119281Z     result = self._find_using_specific_tenant(tenant, token_entry[_ACCESS_TOKEN])
2021-06-15T18:01:17.7120084Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\cli\core\_profile.py", line 1033, in _find_using_specific_tenant
2021-06-15T18:01:17.7120604Z     client = self._arm_client_factory(token_credential)
2021-06-15T18:01:17.7121089Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\cli\core\_profile.py", line 881, in create_arm_client_factory
2021-06-15T18:01:17.7121619Z     base_url=self.cli_ctx.cloud.endpoints.resource_manager, **client_kwargs)
2021-06-15T18:01:17.7122847Z TypeError: __init__() got an unexpected keyword argument 'user_agent'
2021-06-15T18:01:17.7123254Z To open an issue, please run: 'az feedback'
2021-06-15T18:01:17.7158009Z ##[error]Error Code: [1]
2021-06-15T18:01:17.7170024Z ##[debug]Processed: ##vso[task.issue type=error;]Error Code: [1]
2021-06-15T18:01:17.7171137Z ##[error]Error: Azure login failed
2021-06-15T18:01:17.7171762Z ##[debug]Processed: ##vso[task.issue type=error;]Error: Azure login failed
2021-06-15T18:01:17.7172797Z ##[debug]task result: Failed
2021-06-15T18:01:17.7182189Z ##[error]Script failed with error: ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: __init__() got an unexpected keyword argument 'user_agent'
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\knack\cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\cli\core\commands\__init__.py", line 657, in execute
    raise ex
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\cli\core\commands\__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\cli\core\commands\__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\cli\core\commands\__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\cli\core\commands\command_operation.py", line 121, in handler
    return op(**command_args)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\cli\command_modules\profile\custom.py", line 161, in login
    use_cert_sn_issuer=use_cert_sn_issuer)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\cli\core\_profile.py", line 216, in find_subscriptions_on_login
    username, sp_auth, tenant, self._ad_resource_uri)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\cli\core\_profile.py", line 939, in find_from_service_principal_id
    result = self._find_using_specific_tenant(tenant, token_entry[_ACCESS_TOKEN])
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\cli\core\_profile.py", line 1033, in _find_using_specific_tenant
    client = self._arm_client_factory(token_credential)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\cli\core\_profile.py", line 881, in create_arm_client_factory
    base_url=self.cli_ctx.cloud.endpoints.resource_manager, **client_kwargs)
TypeError: __init__() got an unexpected keyword argument 'user_agent'
To open an issue, please run: 'az feedback'

2021-06-15T18:01:17.7191355Z ##[debug]Processed: ##vso[task.issue type=error;]Script failed with error: ERROR: The command failed with an unexpected error. Here is the traceback:%0D%0AERROR: __init__() got an unexpected keyword argument 'user_agent'%0D%0ATraceback (most recent call last):%0D%0A  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\knack\cli.py", line 231, in invoke%0D%0A    cmd_result = self.invocation.execute(args)%0D%0A  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\cli\core\commands\__init__.py", line 657, in execute%0D%0A    raise ex%0D%0A  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\cli\core\commands\__init__.py", line 720, in _run_jobs_serially%0D%0A    results.append(self._run_job(expanded_arg, cmd_copy))%0D%0A  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\cli\core\commands\__init__.py", line 691, in _run_job%0D%0A    result = cmd_copy(params)%0D%0A  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\cli\core\commands\__init__.py", line 328, in __call__%0D%0A    return self.handler(*args, **kwargs)%0D%0A  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\cli\core\commands\command_operation.py", line 121, in handler%0D%0A    return op(**command_args)%0D%0A  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\cli\command_modules\profile\custom.py", line 161, in login%0D%0A    use_cert_sn_issuer=use_cert_sn_issuer)%0D%0A  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\cli\core\_profile.py", line 216, in find_subscriptions_on_login%0D%0A    username, sp_auth, tenant, self._ad_resource_uri)%0D%0A  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\cli\core\_profile.py", line 939, in find_from_service_principal_id%0D%0A    result = self._find_using_specific_tenant(tenant, token_entry[_ACCESS_TOKEN])%0D%0A  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\cli\core\_profile.py", line 1033, in _find_using_specific_tenant%0D%0A    client = self._arm_client_factory(token_credential)%0D%0A  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\cli\core\_profile.py", line 881, in create_arm_client_factory%0D%0A    base_url=self.cli_ctx.cloud.endpoints.resource_manager, **client_kwargs)%0D%0ATypeError: __init__() got an unexpected keyword argument 'user_agent'%0D%0ATo open an issue, please run: 'az feedback'%0D%0A
2021-06-15T18:01:17.7204443Z ##[debug]Processed: ##vso[task.complete result=Failed;]Script failed with error: ERROR: The command failed with an unexpected error. Here is the traceback:%0D%0AERROR: __init__() got an unexpected keyword argument 'user_agent'%0D%0ATraceback (most recent call last):%0D%0A  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\knack\cli.py", line 231, in invoke%0D%0A    cmd_result = self.invocation.execute(args)%0D%0A  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\cli\core\commands\__init__.py", line 657, in execute%0D%0A    raise ex%0D%0A  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\cli\core\commands\__init__.py", line 720, in _run_jobs_serially%0D%0A    results.append(self._run_job(expanded_arg, cmd_copy))%0D%0A  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\cli\core\commands\__init__.py", line 691, in _run_job%0D%0A    result = cmd_copy(params)%0D%0A  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\cli\core\commands\__init__.py", line 328, in __call__%0D%0A    return self.handler(*args, **kwargs)%0D%0A  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\cli\core\commands\command_operation.py", line 121, in handler%0D%0A    return op(**command_args)%0D%0A  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\cli\command_modules\profile\custom.py", line 161, in login%0D%0A    use_cert_sn_issuer=use_cert_sn_issuer)%0D%0A  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\cli\core\_profile.py", line 216, in find_subscriptions_on_login%0D%0A    username, sp_auth, tenant, self._ad_resource_uri)%0D%0A  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\cli\core\_profile.py", line 939, in find_from_service_principal_id%0D%0A    result = self._find_using_specific_tenant(tenant, token_entry[_ACCESS_TOKEN])%0D%0A  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\cli\core\_profile.py", line 1033, in _find_using_specific_tenant%0D%0A    client = self._arm_client_factory(token_credential)%0D%0A  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\cli\core\_profile.py", line 881, in create_arm_client_factory%0D%0A    base_url=self.cli_ctx.cloud.endpoints.resource_manager, **client_kwargs)%0D%0ATypeError: __init__() got an unexpected keyword argument 'user_agent'%0D%0ATo open an issue, please run: 'az feedback'%0D%0A
2021-06-15T18:01:17.7214536Z ##[section]Finishing: Train & Register Model

**To Reproduce**
run an python script from cli

**Expected behavior**
should work fine with 2.25.0 as well

**Environment summary**
azure cli 2.25.0 on MS hosted agents for Azure DevOps

**Additional context**

**Comment by yonzhan** [comment]
route to service team

**Comment by jiasli** [comment]
The error 

```
2021-06-15T18:01:17.7121089Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\cli\core\_profile.py", line 881, in create_arm_client_factory
2021-06-15T18:01:17.7121619Z     base_url=self.cli_ctx.cloud.endpoints.resource_manager, **client_kwargs)
2021-06-15T18:01:17.7122847Z TypeError: __init__() got an unexpected keyword argument 'user_agent'
```

happens at

https://github.com/Azure/azure-cli/blob/3b17a5fb2fd9eb3c35c83cc94245c11d268e7323/src/azure-cli-core/azure/cli/core/_profile.py#L880-L881

`user_agent` is added to `client_kwargs` for Track 2 SDK by

https://github.com/Azure/azure-cli/blob/672837983df7e6f4cb55fadd30ed375bfd53df21/src/azure-cli-core/azure/cli/core/commands/client_factory.py#L127

It looks like the `azure-mgmt-resource` SDK on the agent is not updated to Track 2.

Azure CLI does require Track 2 `azure-mgmt-resource` SDK:

https://github.com/Azure/azure-cli/blob/5cbb798ac28c07ef3453be4f960fce8d17c81f4e/src/azure-cli/setup.py#L118

Could you run 

```
C:\hostedtoolcache\windows\Python\3.7.9\x64\python.exe -m pip list
```

and share the result?

You may install Azure CLI again

```
C:\hostedtoolcache\windows\Python\3.7.9\x64\python.exe -m pip install --upgrade azure-cli 
```

so that the responding SDKs are installed.

**Comment by jiasli** [comment]
Let's work on #18626 instead.
