### ISSUE TITLE
`az container create` fails with `AttributeError: 'ResourcesOperations' object has no attribute 'create_or_update'`

### ISSUE THREAD

**Issue by ghelyar** [Azure/azure-cli#18276]
## Describe the bug

**Command Name**
`az container create`

**Errors:**
```
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: 'ResourcesOperations' object has no attribute 'create_or_update'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/container/custom.py", line 113, in create_container
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/container/custom.py", line 407, in _create_update_from_file
AttributeError: 'ResourcesOperations' object has no attribute 'create_or_update'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

```
- task: AzureCLI@2
  inputs:
    azureSubscription: ...
    scriptType: pscore
    scriptLocation: inlineScript
    inlineScript: |
	  az group create --location LOCATION --name RG_NAME
	  az container create -g RG_NAME -n ACI_NAME -f aci.yml
```

## Environment Summary
Azure DevOps hosted agent: [windows-2019](https://github.com/actions/virtual-environments/tree/main/images/win)
```
C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" --version"
azure-cli                         2.24.0

core                              2.24.0
telemetry                          1.0.6

Extensions:
azure-devops                      0.18.0

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Program Files\Common Files\AzureCliExtensionDirectory'

Python (Windows) 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 13:22:56) [MSC v.1928 32 bit (Intel)]

```
## Additional Context

This was working on 2021-05-27 with 2.23.0, and started failing on 2021-05-28 with 2.24.0

Note that I started getting [an error with `az container exec`](https://github.com/Azure/azure-cli/issues/18275) a few days ago, but now I'm not even getting that far, and it's failing on `az container create` instead.

**Comment by yonzhan** [comment]
route to service team

**Comment by dunlopkr** [comment]
Another thread which looks to be the same issue:
https://github.com/Azure/azure-cli/issues/18291

**Comment by jiasli** [comment]
The error is caused by https://github.com/Azure/azure-cli/blob/4a5d74215d5d1566f839c2d11fd360d300f56b62/src/azure-cli/azure/cli/command_modules/container/custom.py#L407 during `azure-mgmt-resource` SDK track 2 migration (https://github.com/Azure/azure-cli/pull/17783).

Service team needs to figure out why this command and this code path is not covered by the scenario test.

**Comment by yonzhan** [comment]
Add @zhoxing-ms to help with

**Comment by zhoxing-ms** [comment]
@gpatkos This patch will be released in the `CloudShell` in 06-15, may I ask if this time is acceptable?

**Comment by gpatkos** [comment]
@zhoxing-ms: That seems very late. As you may have read on other (duplicated) tickets, this is a blocking issue for a lot of development teams, including ours. Please release it ASAP! Thank you!

**Comment by zhoxing-ms** [comment]
@gpatkos OK, I have initiated the communication with `Cloud Shell` team, hoping to release this patch as soon as possible. However, the release time of this patch depends on the work of `Cloud Shell` team.

**Comment by zhoxing-ms** [comment]
@ghelyar Hi, the hotfix for this issue has been released on some platforms. But for Azure pipeline, we need to cooperate with Azure DevOps team to release this hotfix in the VM of pipeline as soon as possible.
Before that, maybe you can try a work around to solve this issue temporarily:
Execute the command `az upgrade --yes` *(please note that you may need `sudo` permission to execute it)* in the scripts of Azure pipeline to upgrade the CLI to latest version.

**Comment by gpatkos** [comment]
@zhoxing-ms Wonderful! Thanks and we look forward to the fix! Is it possible to get a notification of a successful release here as well?

**Comment by dunlopkr** [comment]
Ubuntu hosted agents were updated to azure-cli 2.24.0 today.  You can add the following bash script to your DevOps release pipeline to install 2.24.2 with the above hotfix:

`curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash`

**Comment by zhoxing-ms** [comment]
@gpatkos OK, it will be released over the weekend if there are no issues

**Comment by zhoxing-ms** [comment]
There is an another workaround https://github.com/actions/virtual-environments/issues/3508#issuecomment-853141701 from ADO team to upgrade the CLI version in Azure Pipeline.

**Comment by kimmatthiesen** [comment]
Its a bug in version 2.24.0 that is fixed in 2.24.2. and since you can upgrade the Azure CLI yourself.. only options, is to wait for ms to upgrade the Azure cli version or to deploy the container from a remote machine.
What i did to get arround the bug was to.:

1.) Download/Installe the Az module on a local machin with powershell installed : https://aka.ms/installazurecliwindows
2.) From Powershell do a .:  [PS] az login
3,) Followin that, and having the .yml file locally you can deploy the container : (i use a command like below)
    [PS] az container create --resource-group RG_ABC --file deploy.yml

(maybe this can help someone)

**Comment by zhoxing-ms** [comment]
@gpatkos This release has completed in `CloudShell`, please have a try~

**Comment by gpatkos** [comment]
@zhoxing-ms Thank you! We have tried it and it works!
