### ISSUE TITLE
az aks get-credentials  not working with the cli azure-cli (2.0.24) on mac

### ISSUE THREAD

**Issue by aumanjoa** [Azure/azure-cli#5267]
running this command

`az aks get-credentials`

returns this error

> 'ManagedCluster' object has no attribute 'properties'
> Traceback (most recent call last):
>   File "/usr/local/Cellar/azure-cli/2.0.24/libexec/lib/python3.6/site-packages/knack/cli.py", line 193, in invoke
>     cmd_result = self.invocation.execute(args)
>   File "/usr/local/Cellar/azure-cli/2.0.24/libexec/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 319, in execute
>     six.reraise(*sys.exc_info())
>   File "/usr/local/Cellar/azure-cli/2.0.24/libexec/lib/python3.6/site-packages/six.py", line 693, in reraise
>     raise value
>   File "/usr/local/Cellar/azure-cli/2.0.24/libexec/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 292, in execute
>     result = cmd(params)
>   File "/usr/local/Cellar/azure-cli/2.0.24/libexec/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 169, in __call__
>     return super(AzCliCommand, self).__call__(*args, **kwargs)
>   File "/usr/local/Cellar/azure-cli/2.0.24/libexec/lib/python3.6/site-packages/knack/commands.py", line 109, in __call__
>     return self.handler(*args, **kwargs)
>   File "/usr/local/Cellar/azure-cli/2.0.24/libexec/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 328, in default_command_handler
>     result = op(**command_args)
>   File "/usr/local/Cellar/azure-cli/2.0.24/libexec/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 1329, in aks_get_credentials
>     access_profiles = mc.properties.access_profiles
> AttributeError: 'ManagedCluster' object has no attribute 'properties'

I have updated the cli using brew upgrade on a mac with macOS High Sierra

**Comment by aumanjoa** [comment]
known issue https://github.com/Azure/AKS/issues/113
