### ISSUE TITLE
Cannot even login since update to 2.0.68

### ISSUE THREAD

**Issue by caoh** [Azure/azure-cli#9920]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
'str' object has no attribute 'get'
Traceback (most recent call last):
python3.7/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 575, in execute
    raise ex
cli/core/commands/__init__.py, ln 633, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 626, in _run_job
    six.reraise(*sys.exc_info())
...
azure/cli/core/_profile.py, ln 946, in adal_token_cache
    return self.load_adal_token_cache()
azure/cli/core/_profile.py, ln 952, in load_adal_token_cache
    self._load_service_principal_creds(all_entries)
azure/cli/core/_profile.py, ln 979, in _load_service_principal_creds
    if c.get(_SERVICE_PRINCIPAL_ID):
AttributeError: 'str' object has no attribute 'get'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login --use-device-code`

## Environment Summary
```
Darwin-18.6.0-x86_64-i386-64bit
Python 3.7.4
Shell: bash

azure-cli 2.0.68

Extensions:
aks-preview 0.4.5
resource-graph 0.1.11

```

**Comment by marstr** [comment]
Sorry you're running into trouble, @caoh. Can you try running an `az account clear` and trying again?

**Comment by caoh** [comment]
No command works anymore. I was trying to use az aks, but az login stopped working altogether. I've already tried uninstall and reinstalling both Python and azure-cli.

**Comment by caoh** [comment]
I had to go and delete the ~/.azure/accessTokens.json to get things to work again. Regardless, it isn't a problem that occurs in my opinion.

**Comment by marstr** [comment]
It seems it was your cache getting invalidated that caused this issue. We're working on re-writing the way our caching mechanism works all together, so I'm going to close this issue out. Sorry you ran into this trouble!
