### ISSUE TITLE
why this command not working???

### ISSUE THREAD

**Issue by Phoenix1112** [Azure/azure-cli#19313]
## Describe the bug

**Command Name**
`az network traffic-manager profile check-dns`

**Errors:**
```
cannot import name 'BatchManagementClient' from 'azure.mgmt.batch' (/usr/lib/python3/dist-packages/azure/mgmt/batch/__init__.py)
Traceback (most recent call last):
python3/dist-packages/knack/cli.py, ln 231, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 558, in execute
    self.commands_loader.load_arguments(command)
...
network/private_link_resource_and_endpoint_connections/resource_providers/batch_provider.py, ln 6, in <module>
    from azure.mgmt.batch import BatchManagementClient
ImportError: cannot import name 'BatchManagementClient' from 'azure.mgmt.batch' (/usr/lib/python3/dist-packages/azure/mgmt/batch/__init__.py)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network traffic-manager profile check-dns {}`

## Environment Summary
```
Linux-5.10.0-kali9-amd64-x86_64-with-glibc2.31
Python 3.9.2
Installer: DEB

azure-cli 2.18.0 *

Extensions:
azure-devops 0.19.0

```

**Comment by yonzhan** [comment]
@kairu-ms for awareness

**Comment by devigned** [comment]
Running into the same issue with `az network nic ip-config create -h`.

**Comment by devigned** [comment]
Similar: https://github.com/Azure/azure-cli/issues/19122

**Comment by devigned** [comment]
This is a pretty common problem as evidenced by the handful of similar items I've linked above. `az upgrade` does not fix the issue with Ubuntu 21.04. Please don't just state run `az upgrade` and close the issue.

When running `sudo apt install azure-cli`, the CLI should work on Ubuntu 21.04.

**Comment by Phoenix1112** [comment]
i am using kali linux .. i did run this command ```az upgrade``` ...  i have this error ```CLI upgrade failed or aborted```
I am getting the same error even though I have tried this many times.

```
└─$ sudo az upgrade
[sudo] password for cyberthereaper: 
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Your current Azure CLI version is 2.18.0. Latest version available is 2.27.1.
Please check the release notes first: https://docs.microsoft.com/cli/azure/release-notes-azure-cli
Do you want to continue? (Y/n): y
Aynı:  1 http://dl.google.com/linux/chrome/deb stable InRelease
Aynı:  3 http://dl.google.com/linux/earth/deb stable InRelease                                  
Aynı:  2 http://kali.download/kali kali-rolling InRelease              
Aynı:  4 https://download.sublimetext.com apt/stable/ InRelease
Paket listeleri okunuyor... Bitti
Paket listeleri okunuyor... Bitti
Bağımlılık ağacı oluşturuluyor... Bitti
Durum bilgisi okunuyor... Bitti               
azure-cli zaten en yeni sürümde (2.18.0-2).
0 paket yükseltilecek, 0 yeni paket kurulacak, 0 paket kaldırılacak ve 268 paket yükseltilmeyecek.
CLI upgrade failed or aborted.
```

**Comment by Phoenix1112** [comment]
also i hav error for this method..

```
┌──(cyberthereaper㉿kali)-[~]
└─$ curl -sL https://packages.microsoft.com/keys/microsoft.asc |
    gpg --dearmor |
    sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
```

```
┌──(cyberthereaper㉿kali)-[~]
└─$ AZ_REPO=$(lsb_release -cs)
echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" |
    sudo tee /etc/apt/sources.list.d/azure-cli.list
deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ kali-rolling main

```

```
┌──(cyberthereaper㉿kali)-[~]
└─$ sudo apt update
Aynı:  1 http://dl.google.com/linux/chrome/deb stable InRelease
Aynı:  2 http://dl.google.com/linux/earth/deb stable InRelease                                                                                                                     
Yoksay:3 https://packages.microsoft.com/repos/azure-cli kali-rolling InRelease                                                                                                     
Hata:  4 https://packages.microsoft.com/repos/azure-cli kali-rolling Release                                                                            
  404  Not Found [IP: 104.214.230.139 443]
Aynı:  5 http://kali.download/kali kali-rolling InRelease              
Aynı:  6 https://download.sublimetext.com apt/stable/ InRelease
Paket listeleri okunuyor... Bitti                          
E: 'https://packages.microsoft.com/repos/azure-cli kali-rolling Release' deposunda Release dosyası yok.
N: Böyle bir depodan güvenli bir şekilde güncelleme yapılamaz, bu nedenle depo devre dışı bırakılmıştır.
N: Depo oluşturma ve kullanıcı yapılandırması hakkında ayrıntılı bilgi için apt-secure(8) rehber sayfasında bulunabilir.
```

**Comment by jiasli** [comment]
I noticed a weird thing. The DEB installer of Azure CLI has its bundled Python 3.6.10.

```
$ az -v
azure-cli                         2.27.2

core                              2.27.2
...

Python location '/opt/az/bin/python3'
Extensions directory '/home/user1/.azure/cliextensions'

Python (Linux) 3.6.10 (default, Aug 23 2021, 03:36:00)
[GCC 9.3.0]
```

But in all linked issues, Python is 3.9.*:

```
Linux-5.10.0-kali9-amd64-x86_64-with-glibc2.31
Python 3.9.2
Installer: DEB
```

Could you let me know the OS you are using by running

```
$ cat /etc/os-release
```

**Comment by devigned** [comment]
Below is my remove and install experience on Ubuntu 21.04. Looks like both Kali and Ubuntu are not able to find the MSFT published package and are installing a default version 2.18.0 (`Get:1 http://us.archive.ubuntu.com/ubuntu hirsute/universe amd64 azure-cli all 2.18.0-1 [2,608 B]`).

```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="21.04 (Hirsute Hippo)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 21.04"
VERSION_ID="21.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
```

```
david at tadashi in ~/code/k8s/capz on main [$]
$ sudo apt remove azure-cli -y && sudo apt autoremove -y
[sudo] password for david: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages will be REMOVED:
  azure-cli
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 15.4 kB disk space will be freed.
(Reading database ... 245063 files and directories currently installed.)
Removing azure-cli (2.18.0-1) ...
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

david at tadashi in ~/code/k8s/capz on main [$]
$ curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
Hit:1 http://dl.google.com/linux/chrome/deb stable InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu hirsute InRelease                                                       
Get:3 http://us.archive.ubuntu.com/ubuntu hirsute-updates InRelease [109 kB]                                      
Ign:4 https://packages.microsoft.com/repos/azure-cli hirsute InRelease                                                      
Err:5 https://packages.microsoft.com/repos/azure-cli hirsute Release                         
  404  Not Found [IP: 13.82.67.141 443]
Get:6 http://us.archive.ubuntu.com/ubuntu hirsute-backports InRelease [101 kB]
Get:7 http://us.archive.ubuntu.com/ubuntu hirsute-backports/universe amd64 DEP-11 Metadata [9,264 B]
Get:8 http://security.ubuntu.com/ubuntu hirsute-security InRelease [101 kB]    
Reading package lists... Done         
E: The repository 'https://packages.microsoft.com/repos/azure-cli hirsute Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

david at tadashi in ~/code/k8s/capz on main [$]
$ sudo apt install azure-cli
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  azure-cli
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 2,608 B of archives.
After this operation, 15.4 kB of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu hirsute/universe amd64 azure-cli all 2.18.0-1 [2,608 B]
Fetched 2,608 B in 0s (19.8 kB/s)     
Selecting previously unselected package azure-cli.
(Reading database ... 245058 files and directories currently installed.)
Preparing to unpack .../azure-cli_2.18.0-1_all.deb ...
Unpacking azure-cli (2.18.0-1) ...
Setting up azure-cli (2.18.0-1) ...
```
