### PR TITLE
[App Service] Fix #22722: `az webapp config ssl import` fixes to support new GraphAPI for SP queries

### LINKED ISSUE #22722: `az webapp config ssl import` fails: AttributeError: 'GraphClient' object has no attribute 'service_principals'
## Description

**Command Name**
`az webapp config ssl import`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'GraphClient' object has no attribute 'service_principals'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 718, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/commands.py", line 39, in _ex_handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 2700, in import_ssl_cert
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 2779, in _check_service_principal_permissions
AttributeError: 'GraphClient' object has no attribute 'service_principals'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

```
az webapp config ssl import --resource-group [VALID RESOURCE GROUP ON SAME SUBSCRIPTION] --name [VALID APP SERVICE ON RESOURCE GROUP] --key-vault '/subscriptions/[VALID SUBSCRIPTION]/resourceGroups/[VALID RESOURCE GROUP]/providers/Microsoft.KeyVault/vaults/[VALID KEYVAULT ON RESOURCE GROUP]' --key-vault-certificate-name [VALID CERTIFICATE ON KEYVAULT]
```

## Expected Behavior
This worked fine with Azure CLI v2.35

## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.4
Installer: MSI

azure-cli 2.37.0

Extensions:
application-insights 0.1.16
azure-cli-iot-ext 0.8.10
azure-devops 0.25.0
azure-iot 0.14.1
databricks 0.8.0
log-analytics 0.2.2
portal 0.1.2
resource-graph 2.1.0
storage-preview 0.8.3
subscription 0.1.5

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

### PR DESCRIPTION
**Pull request by panchagnula**
Fixes #22722

**Related command**

**Description**

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
App Service

**Comment by panchagnula** [comment]
@zhoxing-ms / @wangzelin007 can we merge this change?

**Review by zhoxing-ms — APPROVED** [review]

**Comment by zhoxing-ms** [comment]
@jiasli Please help review the Graph related changes

**Review by jiasli — APPROVED** [review]
