### ISSUE TITLE
az sig image-version list - fails to work azure-cli 2.41.0

### ISSUE THREAD

**Issue by psiservices-jerrybrimacombe** [Azure/azure-cli#24310]
## Describe the bug

**Command Name**
`az sig image-version list`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'ComputeManagementClientConfiguration' object has no attribute 'api_version'
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 710, in _run_job
    result = list(result)
  File "/opt/az/lib/python3.10/site-packages/azure/core/paging.py", line 129, in __next__
    return next(self._page_iterator)
  File "/opt/az/lib/python3.10/site-packages/azure/core/paging.py", line 76, in __next__
    self._response = self._get_next(self.continuation_token)
  File "/opt/az/lib/python3.10/site-packages/azure/mgmt/compute/v2022_01_03/operations/_gallery_image_versions_operations.py", line 1052, in get_next
    request = prepare_request(next_link)
  File "/opt/az/lib/python3.10/site-packages/azure/mgmt/compute/v2022_01_03/operations/_gallery_image_versions_operations.py", line 1037, in prepare_request
    _next_request_params["api-version"] = self._config.api_version
AttributeError: 'ComputeManagementClientConfiguration' object has no attribute 'api_version'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az sig image-version list --gallery-image-definition {} --gallery-name {} --resource-group {}`

## Expected Behavior
Return the list of image versions

## Environment Summary
```
Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.31, Ubuntu 20.04.5 LTS
Python 3.10.5
Installer: DEB

azure-cli 2.41.0

Extensions:
fzf 1.0.2
storage-preview 0.8.3
azure-devops 0.25.0
scheduled-query 0.5.1
resource-graph 2.1.0
application-insights 0.1.16
account 0.2.5
image-copy-extension 0.2.9

Dependencies:
msal 1.20.0b1
azure-mgmt-resource 21.1.0b1
```
## Additional Context

Was working with version azure-cli 2.40.0

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness

**Comment by zhoxing-ms** [comment]
Known issue, and its essence is also an SDK issue. https://github.com/Azure/azure-cli/issues/24187#issuecomment-1278384023
We will release a new CLI version on 11-01 to fix the issue. Please update the CLI version and try again at that time
