### ISSUE TITLE
WebApp:az webapp config access-restriction remove broke since 2.26.0

### ISSUE THREAD

**Issue by RobHofmann** [Azure/azure-cli#18947]
## Describe the bug

**Command Name**
`az webapp config access-restriction remove`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/access_restrictions.py", line 120, in remove_webapp_access_restriction
AttributeError: 'NoneType' object has no attribute 'lower'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp config access-restriction remove --resource-group {ResourceGroupName} --name {WebAppName} --action Allow --scm-site True --subnet {SubnetResourceId}`

## Expected Behavior
Successful removal of an access-restriction rule.

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.26.1

Extensions:
azure-devops 0.18.0

```
## Additional Context
I just tested this. This was working in 2.25.0 and before. With 2.26.0+ it doesn't work anymore.

**Comment by yonzhan** [comment]
route to service team
