### PR TITLE
{Core} Only lower provisioning_state when it has value

### PR DESCRIPTION
**Pull request by jiasli**
Fix the regression in https://github.com/Azure/azure-cli/pull/12154: `provisioning_state.casefold()` raises exception `AttributeError: 'NoneType' object has no attribute 'casefold'` when `provisioning_state` is `None`.

This causes issue to `az sql server wait` since sql server doesn't use `"provisioningState": "Succeeded"`, but `"state": "Ready"`: https://github.com/Azure/azure-cli/issues/12313

Only lower `provisioning_state` when it has value (not `None` or empty string `''`).

Tested with

```
az vm wait --ids {} --created
```

Also, use `lower()` to be consistent with other code.

### CODE REVIEW

**Comment by Juliehzl** [comment]
My concern is that although your current change will not break users ay more, the sql wait command still doesn't work now.
I mean because the wait condition is from "state" and "provisionstate" will none, the wait condition will never match as expected for this scenario.

**Comment by jiasli** [comment]
> My concern is that although your current change will not break users ay more, the sql wait command still doesn't work now.
> I mean because the wait condition is from "state" and "provisionstate" will none, the wait condition will never match as expected for this scenario.

I have put my thought in https://github.com/Azure/azure-cli/issues/12313#issuecomment-597423556. But anyway, let's fix the regression first.
