### ISSUE TITLE
Error on running az bicep version

### ISSUE THREAD

**Issue by ElYusubov** [Azure/azure-cli#17718]
## Describe the bug

**Command Name**
`az bicep version`

**Errors:**
The command failed with an unexpected error. Here is the traceback:
type object 'datetime.datetime' has no attribute 'fromisoformat'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 807, in default_command_handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/custom.py", line 3302, in show_bicep_cli_version
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/_bicep.py", line 63, in run_bicep_command
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/_bicep.py", line 152, in _load_bicep_version_check_result_from_cache
AttributeError: type object 'datetime.datetime' has no attribute 'fromisoformat'

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az bicep version`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.22.0

Extensions:
account 0.2.1
interactive 0.4.4

```
## Additional Context

This happened after upgrading "az cli" to latest version and then updating az bicep

**Comment by yonzhan** [comment]
route to service team

**Comment by ElYusubov** [comment]
Even when installing fresh Azure CLI for windows OS, i see the same error when running `az bicep version` command.
Please, escalate asap.

**Comment by davidschlum** [comment]
After updating to the latest Azure CLI (2.22.0) for Windows 10, I am now seeing the same error as others have reported:

Any command such as "az bicep version" is producing the following error:

The command failed with an unexpected error. Here is the traceback:
type object 'datetime.datetime' has no attribute 'fromisoformat'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 807, in default_command_handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/custom.py", line 3294, in build_bicep_file
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/_bicep.py", line 63, in run_bicep_command
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/_bicep.py", line 152, in _load_bicep_version_check_result_from_cache
AttributeError: type object 'datetime.datetime' has no attribute 'fromisoformat'

**Comment by davidschlum** [comment]
FYI - I uninstalled Azure CLI 2.22.0 and installed 2.21.0 and confirmed that the 2.21.0 version did not have the problem reported.

**Comment by ElYusubov** [comment]
Just to complement what @davidschlum mentioned check the links for installation.
Check following sources to get your 2.21.0 version below:

- https://github.com/Azure/azure-cli/releases
- https://community.chocolatey.org/packages/azure-cli/2.21.0

**Comment by smokedlinq** [comment]
I just installed 2.22.1 and this fixes this issue, at least for me. 👍

**Comment by JQUINONES82** [comment]
My Azure Shell is broken now as it was upgrade and bicep does not work.  I can fix this by installing on premise.

**Comment by dahol** [comment]
Just encountered this one, rollback to version 2.22.1 works as expected.

**Comment by mnj** [comment]
Ran in to this issue as well on the mentioned versions, after upgrading to 2.24.2 it's working fine here again.

**Comment by aggelosdani** [comment]
any final solution?

**Comment by ElYusubov** [comment]
If you run this issue, try the following steps as solution:

1. Update your AZ CLI version
2. Upgrade the az bicep version
3. Downgrade the az bicep version if "Step 2" did not help you 👍

Hope this instructions will help you to troubleshoot the similar error that you have.
