### ISSUE TITLE
WebApp:Azure webapp backup restore is not working in version 2.30.0

### ISSUE THREAD

**Issue by IgnacioAlvarezArenas** [Azure/azure-cli#20470]
**Describe the bug**
Running a restore of an App Service backup is returning an error:

Command
az webapp config backup restore --resource-group RGName --webapp-name AppServiceName --backup-name BackupID --container-url "URLofStorageaccountURL"

The command failed with an unexpected error. Here is the traceback:
'WebAppsOperations' object has no attribute 'restore'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 712, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/commands.py", line 37, in _ex_handler
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 1861, in restore_backup
    return client.web_apps.restore(resource_group_name, webapp_name, 0, restore_request)
AttributeError: 'WebAppsOperations' object has no attribute 'restore

This happens with this version:
 az --version
azure-cli                         2.30.0

core                              2.30.0
telemetry                          1.0.6

Extensions:
vm-repair                          0.2.5
ai-examples                        0.2.5
ssh                                0.1.8

Python location '/opt/az/bin/python3'
Extensions directory '/home/ignacio/.azure/cliextensions'
Extensions system directory '/opt/az/lib/python3.6/site-packages/azure-cli-extensions'

**To Reproduce**
Run AzureCLI in the Portal (version 2.30.0):
az webapp config backup restore --resource-group RGName --webapp-name AppServiceName --backup-name BackupID --container-url "URLofStorageaccountURL"

**Expected behavior**
It should trigger a backup restore

**Environment summary**
App Service without any Networking features enabled

**Comment by yonzhan** [comment]
route to service team

**Comment by Kotasudhakarreddy** [comment]
Duplicate of #19492
