### ISSUE TITLE
AttributeError: 'ContainerServiceClientConfiguration' object has no attribute 'api_version'

### ISSUE THREAD

**Issue by vishalv-rafay** [Azure/azure-cli#31664]
## Describe the bug

**Command Name**
`az aks nodepool list`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'ContainerServiceClientConfiguration' object has no attribute 'api_version'
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.41.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.41.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.41.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.41.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 710, in _run_job
    result = list(result)
  File "/opt/homebrew/Cellar/azure-cli/2.41.0/libexec/lib/python3.10/site-packages/azure/core/paging.py", line 129, in __next__
    return next(self._page_iterator)
  File "/opt/homebrew/Cellar/azure-cli/2.41.0/libexec/lib/python3.10/site-packages/azure/core/paging.py", line 76, in __next__
    self._response = self._get_next(self.continuation_token)
  File "/opt/homebrew/Cellar/azure-cli/2.41.0/libexec/lib/python3.10/site-packages/azure/mgmt/containerservice/v2022_07_01/operations/_agent_pools_operations.py", line 406, in get_next
    request = prepare_request(next_link)
  File "/opt/homebrew/Cellar/azure-cli/2.41.0/libexec/lib/python3.10/site-packages/azure/mgmt/containerservice/v2022_07_01/operations/_agent_pools_operations.py", line 391, in prepare_request
    _next_request_params["api-version"] = self._config.api_version
AttributeError: 'ContainerServiceClientConfiguration' object has no attribute 'api_version'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks nodepool list --resource-group {} --cluster-name {} --query {} --output {}`

## Environment Summary
```
macOS-12.3-arm64-arm-64bit, Darwin 21.4.0
Python 3.10.8
Installer: HOMEBREW

azure-cli 2.41.0 *
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by mbifeld** [comment]
Hi @vishalv-rafay, I see you're on Azure CLI 2.41. I believe this issue was fixed in https://github.com/Azure/azure-cli/pull/24270. Can you upgrade your cli to the latest version (2.74) and see if the issue persists?

**Comment by mbifeld** [comment]
Hi @vishalv-rafay, can you confirm if upgrading the cli version worked?

**Comment by vishalv-rafay** [comment]
It did not work from MAC with M1 but worked in Ubuntu 22.04 . please close the ticket
